### ISSUE TITLE
Problem with checkout card

### ISSUE THREAD

**Issue by jimmyr57000** [grandnode/grandnode#1008]
**Describe the bug**
When I try to buy an item I validate the terms of service then click on the Checkout button the page only refreshes and nothing happens

**To Reproduce**
1. Go to the store and buy a item
2. Click on add to card
3. Agree the terms of service
4. Pressed Checkout and the page just refreshes 

**Desktop (please complete the following information):**
 - Browser: Google Chrome, Edge

**Additional context**
Working on Linux Ubuntu 20.04

Thanks you all !

**Comment by KrzysztofPajak** [comment]
Fixed - problem with conf nginx - more info you can find here [https://grandnode.com/boards/topic/5fa98ebfb47c181cd0aefa69/problem-with-checkout](url)
