### ISSUE TITLE
Problem with syslog

### ISSUE THREAD

**Issue by Illia-M** [grandnode/grandnode#1012]
Now i get around 7GB per day in syslog with around 2 millions requests per day.
Most part of logs from GrandNode stdout(console) and i can not turnoff some logs from appsettings.
What is wrong?

Ubuntu+Nginx+GrandNode 4.8

**Comment by PatrykPorabik** [comment]
I would suggest to use the Serilog loggin, and if you want limit the minimum level of logs here: [https://github.com/grandnode/grandnode/blob/develop/Grand.Web/App_Data/appsettings.json#L161](https://github.com/grandnode/grandnode/blob/develop/Grand.Web/App_Data/appsettings.json#L161)

**Comment by Illia-M** [comment]
Do not close my issues, please.
I set both settings for Asp.Net logging and Serilog to warning and numbers above with this setting.
