### ISSUE TITLE
I think the link is wrong, can you check?

### ISSUE THREAD

**Issue by talhakaanozkan** [grandnode/grandnode#1017]
**Describe the bug**
I think the link is wrong, can you check?

**Additional context**
![image](https://user-images.githubusercontent.com/24568732/99549230-79e33c80-29ca-11eb-8fa6-0106cf69e608.png)

![image](https://user-images.githubusercontent.com/24568732/99549298-8c5d7600-29ca-11eb-8f5f-16ad4fa73728.png)

**Comment by talhakaanozkan** [comment]
by the way, the new "README.md" file is very nice.

**Comment by PatrykPorabik** [comment]
Hi, @talhakaanozkan  Thanks a lot! It's definitely a typo :)
