### ISSUE TITLE
Slow page loads on development

### ISSUE THREAD

**Issue by mehmetcantas** [grandnode/grandnode#1019]
All categories page loads is between 1.5 - 2 seconds (with sample data). Is this normal or I missing something?

OS : Mac OS Big Sur 
Processor : 2.6 GHz 6-Core Intel Core i7
RAM : 16 GB 2667 MHz DDR4

**Comment by PatrykPorabik** [comment]
Hi @mehmetcantas 

To be honest, I don't really know what should I write. We haven't noticed similar problems in our test environment, which is a much simpler machine than your PC. Even our https://demo.grandnode.com/ loads the category pages faster than 1sec.
