### ISSUE TITLE
Moving topic keeping old location

### ISSUE THREAD

**Issue by TTomu** [grandnode/grandnode#1025]
**Describe the bug**
If the forum moderator move topic, from one forum to another, the old forum keeps posts visible. The latest post is also showing the topic in the old one, and the new one is not updated. 

![image](https://user-images.githubusercontent.com/16773048/100072939-24c97f80-2e3d-11eb-823f-5b48f893bf08.png)

**Comment by PatrykPorabik** [comment]
Already reported **"Count down post number when moved post from board topic"** #377
