### ISSUE TITLE
Avatars not load from user 

### ISSUE THREAD

**Issue by TTomu** [grandnode/grandnode#1026]
**Describe the bug**
If the avatar is enabled, each user post avatar is shown from the current user, not an author of the post. 

Below, view if logged as Tim
![image](https://user-images.githubusercontent.com/16773048/100073535-e8e2ea00-2e3d-11eb-8c32-2c483262130f.png)

And view if logged as John
![image](https://user-images.githubusercontent.com/16773048/100073664-14fe6b00-2e3e-11eb-9d84-762df0d75218.png)

**Comment by badijm** [comment]
Hi @TTomu are you refering to blog page or to forum ?  `https://demo.grandnode.com/blog`

**Comment by TTomu** [comment]
@badijm Forum. Apologize for the confusion.

**Comment by badijm** [comment]
Am I using right url for forum ? 

On current url I see no issue: 
https://grandnode.com/boards/topic/5fb5b64106e76702eca745de/categories-and-products

**Comment by PatrykPorabik** [comment]
@badijm check the issue on the newest version of GrandNode downloaded from our GitHub :)
