### ISSUE TITLE
Allowed quantities

### ISSUE THREAD

**Issue by TTomu** [grandnode/grandnode#1038]
**Describe the bug**
Product has allowed quantities of 10/50/100
Not able to add the double value of 10

**To Reproduce**
1. Go to product
2. Click on add to cart quantity of 10
3. Click on the pop up continue to stay at the product page
4. Click again add to cart quantity of 10

**Expected behavior**
In this case, adding a new order line should be executed instead of adding quantity.

**Comment by dborovsky** [comment]
@TTomu Hi! 

How can reproduce this in app? Which settings need I add to product to have quantity for example 10/50/100?

**Comment by TTomu** [comment]
At the product, at the Inventory tab, need to find Allowed quantities :)
![image](https://user-images.githubusercontent.com/16773048/104687845-4427af00-5700-11eb-80d7-7c755cd0edb8.png)

**Comment by dborovsky** [comment]
Yes, has already found. I' fix this issue.
