### ISSUE TITLE
Sitemap.cshtml file instead of SystemName should use SeName to create URLs

### ISSUE THREAD

**Issue by WeiweiCaiAcpt** [grandnode/grandnode#1041]
We added a test topic page from Content Management > Topics (pages), and enable Include in sitemap and Include in menu. After saving and go to Home page, when I click the the new topic page from top menu, it navigate to Home page. If we click from Sitemap, it show page not found.
![image](https://user-images.githubusercontent.com/70355356/101317181-f4e89600-3898-11eb-9427-5e56148f68e4.png)

**Steps to reproduce the behavior:**
1. Click “Administration” icon. 
2. Click “Comment Mangement” item. 
3. Click “Topics (Pages)” item. 
4. Click “Add new” button. 
5. Input “Test topic” in the “Title” text box. 
6. Check in “Include in top menu” option.  
7. Check in “Include in sitemap” option. 
8. Input “Test topic page” in the “system name” text box  
9. Click “Save” button. 
10. Click “Public store” icon. 
11. Click "Test topic" from top menu, it navigated to Home page.
12. Click “Sitemap” link. 
13. Click “Test topic” link, it shows page not found.

**Expected behavior**
Both step 11 and step 13 will navigate to the Test topic page.

**Screenshots**
![image](https://user-images.githubusercontent.com/70355356/101317181-f4e89600-3898-11eb-9427-5e56148f68e4.png)

**Desktop (please complete the following information):**
 - Browser: Microsoft Edge (version 87.0.664.55)

**Additional context**
App version: 
![image](https://user-images.githubusercontent.com/70355356/101317697-f6668e00-3899-11eb-908f-02e06678bc7b.png)

**Comment by PatrykPorabik** [comment]
Hi, @WeiweiCaiAcpt !

Well, in my case it redirected correctly from the top menu. However, in the sitemap, it has a problem. I suppose it's related to spaces in the SeName. We will investigate it, thanks for the bug report.

**Comment by WeiweiCaiAcpt** [comment]
@PatrykPorabik  Thanks for your investigating.

**Comment by PatrykPorabik** [comment]
@Weidaicheng We've found the potential issue. If you are not able to see the topic after saving changes, you probably didn't mark the "Published" option. However, it doesn't change the fact, that there is an issue in the cshtml file. As I checked the code, sitemap.xml contains the correct URL, the problem is only in the view. I will fix it in a moment.
