### ISSUE TITLE
RSS feed generation error

### ISSUE THREAD

**Issue by Illia-M** [grandnode/grandnode#1050]
**Describe the bug**
When product not have description in some localization, empty string(null value) generates error on XML content generation

**To Reproduce**
1. Go to 'https://<shop domian>/<lang code>/newproducts/rss'
2. See error

**Expected behavior**
RSS feed generated

**Screenshots**
![image](https://user-images.githubusercontent.com/64944310/103213961-e29dcd00-4917-11eb-8fa3-6972c89cd1b3.png)

**Additional context**
Ubuntu, GrandNode 4.80

System.ArgumentNullException: Value cannot be null. (Parameter 'value') at System.Xml.Linq.XText..ctor(String value) at System.Xml.Linq.XCData..ctor(String value) at Grand.Framework.Mvc.Rss.RssItem.Init(String title, String content, Uri link, String id, DateTimeOffset pubDate) in C:\Projects\Grandnode\grandnode\Grand.Framework\Mvc\Rss\RssItem.cs:line 55 at Grand.Web.Controllers.ProductController.NewProductsRss(IWebHelper webHelper) in C:\Projects\Grandnode\grandnode\Grand.Web\Controllers\ProductController.cs:line 501 at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Grand.Framework.Middleware.WorkContextMiddleware.Invoke(HttpContext context, IWorkContext workContext) in C:\Projects\Grandnode\grandnode\Grand.Framework\Middleware\WorkContextMiddleware.cs:line 71 at Grand.Framework.Middleware.StoreContextMiddleware.Invoke(HttpContext context, IStoreContext storeContext) in C:\Projects\Grandnode\grandnode\Grand.Framework\Middleware\StoreContextMiddleware.cs:line 44 at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Grand.Framework.Middleware.PoweredByMiddleware.InvokeAsync(HttpContext context, IPoweredByMiddlewareOptions options) in C:\Projects\Grandnode\grandnode\Grand.Framework\Middleware\PoweredByMiddleware.cs:line 27 at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context) at WebMarkupMin.AspNetCore3.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression) at WebMarkupMin.AspNetCore3.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression) at WebMarkupMin.AspNetCore3.WebMarkupMinMiddlewareBase.Invoke(HttpContext context) at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by PatrykPorabik** [comment]
Thanks for the report. We will keep it in mind before the next version release.
