### ISSUE TITLE
plugin upload problem

### ISSUE THREAD

**Issue by Rajat37** [grandnode/grandnode#1082]
![screen09](https://user-images.githubusercontent.com/47422681/108954107-492e3580-7692-11eb-88af-f28ed9e02bfd.jpg)
![screen10](https://user-images.githubusercontent.com/47422681/108954113-4af7f900-7692-11eb-971f-9349a5571ca3.jpg)

**Describe the bug**

**To Reproduce**
1. Go to 'upload google shopping plugin'
2. See error 'page not found'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PatrykPorabik** [comment]
It's not a bug related to the code. Please post this kind of questions on our community forum - [https://grandnode.com/boards](https://grandnode.com/boards)
By the way. This issue usually means that you don't have permissions to upload new files, check if you set proper permissions. Or the second case is that you have an upload limit on your server. More information about this error can be found in System -> Log. It will clearly show you the reason of the problem.
