### ISSUE TITLE
Internal error on google shopping plugin after manual upload and instaling

### ISSUE THREAD

**Issue by Rajat37** [grandnode/grandnode#1083]
![screen11](https://user-images.githubusercontent.com/47422681/108955575-6f54d500-7694-11eb-83bf-dec3301aa3db.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PatrykPorabik** [comment]
Please provide more information about the GrandNode version. Please look at the System -> Log for a full error log. It will clearly show the reason of the problem.

**Comment by PatrykPorabik** [comment]
@Rajat37 please download the package with the plugin again. I've found a typo in the .cshtml file in the plugin which destroys the Configure layout. Thanks for reporting!
