### ISSUE TITLE
Convert picture to webp format is not working

### ISSUE THREAD

**Issue by Rajat37** [grandnode/grandnode#1084]
**Describe the bug**
I upgraded grandnode 4.8 to 4.9, then this issue will come, now my pictures is in jpeg format i tried to convert but still not working, i checked all pictures format on server it is still in jpeg, i uploaded many product pictures in jpeg and try again to convert but not worked

**Desktop (please complete the following information):**
 - Browser [Chrome]

**Smartphone (please complete the following information):**

![screen12](https://user-images.githubusercontent.com/47422681/109107209-56612800-7757-11eb-9fb8-7e15c66969cb.jpg)

**Comment by PatrykPorabik** [comment]
Everything works fine in our test environment. Please provide more details or error log.
