### ISSUE TITLE
Making sidebar prettier

### ISSUE THREAD

**Issue by gauravgupta98** [grandnode/grandnode#1086]
## It'd be nice if we can add logo at the top of the sidebar nav and some padding right will do the magic
The below screenshot is from the demo website available on [Grandnode](https://grandnode.com)
![image](https://user-images.githubusercontent.com/31717079/109415526-3ba0e480-79df-11eb-9484-e7fcba3c3518.png)

**Comment by ssmaithili** [comment]
Hey , I would love to contribute here, can you assign it to me ?

**Comment by gauravgupta98** [comment]
HI @ssmaithili ,

I think someone from grandnode would be able to assign and assist whether they need this update or not.

Thanks.
