### ISSUE TITLE
Azure Picture Service throws while starting app with sample data

### ISSUE THREAD

**Issue by OskarCukrowicz** [grandnode/grandnode#1087]
**Describe the bug**
`StorageException: The specified resource name contains invalid characters.` on Azure Picture Service with default sample data.

**To Reproduce**
1. Git clone this repo
1. Add Azure Storage credentials to appsettings.json
1. Start the app
1. Install GrandNode with 'Create sample data' checkbox enabled
1. Restart the app
1. `StorageException: The specified resource name contains invalid characters.`

It shouldn't throw while trying to create sample data but also the AzurePictureService expecting its users to think about valid filename for a blob in Azure is a leaky abstraction.

**Comment by PatrykPorabik** [comment]
Well, we don't recommend installing GrandNode and sample data with Azure Storage configured. It should be configured after successful installation.

**Comment by ocukrowicz** [comment]
@PatrykPorabik It throws if you install sample data and then configure azure storage too.

**Comment by OskarCukrowicz** [comment]
@PatrykPorabik If I create sample data and then configure azure storage afterward it fails as well.
