### ISSUE TITLE
Grandnode re-write

### ISSUE THREAD

**Issue by scharada** [grandnode/grandnode#1097]
i wish we knew about this a bit earlier. there are some ideas we could suggest to make it shine and special..

**Comment by PatrykPorabik** [comment]
If you want to suggest something, go ahead :)

**Comment by scharada** [comment]
> If you want to suggest something, go ahead :)

true multitenancy
plugin load and unload as per net core 5 and 6
plugin loading by tenant context
paid plugin by tenant
user management as per asp.net with ID server for ACL/claims management
master catalog
all this is easily feasible in a microservice architecture...

**Comment by KrzysztofPajak** [comment]
All information about multitenant to version 2.0 you can find here https://grandnode.com/grandnode-v2-multi-tenancy
