### ISSUE TITLE
Tier Price not working

### ISSUE THREAD

**Issue by Rajat37** [grandnode/grandnode#1098]
Tier Price not working.
Tier price not displayed in Grandnode Frontend 4.90

**Comment by PatrykPorabik** [comment]
Well, I've checked it on our demo environment and everything works fine. Can you provide a steps to reproduce this issue on unmodified, clean environment?

**Comment by Rajat37** [comment]
> Well, I've checked it on our demo environment and everything works fine. Can you provide steps to reproduce this issue in an unmodified, clean environment?

![screen13](https://user-images.githubusercontent.com/47422681/116215534-63a18f80-a765-11eb-80e8-ae6155616308.jpg)
![screen14](https://user-images.githubusercontent.com/47422681/116215552-669c8000-a765-11eb-8d72-d05c7b194102.jpg)

**Comment by TTomu** [comment]
> Tier Price not working.
> Tier price not displayed in Grandnode Frontend 4.90

It is by design. If you will add just a single record of the tier price, it will not be vissble. Add one more, and be able to see that on a frontend.
