### ISSUE TITLE
is it possible to implement an SSR with caching, using Nuxt.js or Quasar

### ISSUE THREAD

**Issue by balajivelu147** [grandnode/grandnode#1100]
as we know ecom totally depends of page speed, caching becames an key asset for that... i have used nextjs(react) - [does caching and loads only the required scripts and css(https://multikart-react.vercel.app/page/account/cart)] which can load project in 500ms. please check if that works out..

**Comment by PatrykPorabik** [comment]
Currently we don't plan to implement it.
