### ISSUE TITLE
Add External Auth via AAD B2C

### ISSUE THREAD

**Issue by AlexJPawlak** [grandnode/grandnode#1104]
**Is your feature request related to a problem? Please describe.**
I'd like to request feature of adding a new Authentication Plugin to allow integration for AAD B2C services - would be a nice addition as the platform already runs heavily on Microsoft stack

**Describe the solution you'd like**
Allow User registration / management on AAD B2C tenant

**Additional context**
AAD B2C sounds like a perfect fit for authentication provider to be included. Maybe at some point in future. I have started some work on getting this done but this likely isn't going to qualify for pull request 

Thanks for great product, I'm building up my store with it and hope to see it live at some point :-)

**Comment by KrzysztofPajak** [comment]
Hi @AlexJPawlak 
This repo is outdated.
Please use this solution https://github.com/grandnode/grandnode2
