### ISSUE TITLE
4.00 - Mobile Application

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#120]
Make an mobile application for GrandNode

**Comment by muhammetsahin** [comment]
I can help make an mobile application for GrandNode using Xamarin.

**Comment by PatrykPorabik** [comment]
Thanks @muhammetsahin. We've finally done it. You can check it on AppStore or Google Play Store. 
https://play.google.com/store/apps/details?id=grandNodeApp.Droid
https://itunes.apple.com/ca/app/grandnode/id1264534347?mt=8
