### ISSUE TITLE
3.90 Fail to install when using mongodb other than (127.0.0.1:27017)

### ISSUE THREAD

**Issue by lifra-esquel** [grandnode/grandnode#128]
Fail to install Grandnode using mongodb other than (127.0.0.1:27017). for example (127.0.0.1:27018).
During the installation, the system will try to connect to 127.0.0.1:27017 which is incorrect.

Please check

**Comment by PatrykPorabik** [comment]
Port 27018 is reserved by MongoDB. You shouldn't use it. Please look at MongoDB docs:
https://docs.mongodb.com/manual/reference/default-mongodb-port/

**Comment by lifra-esquel** [comment]
I see. Port 27018 is just an example. Actually for the port other than 27017 would be fail to install

**Comment by PatrykPorabik** [comment]
Are you able to connect with database using different ports with for example Robomongo, MongoChef or other clients?

**Comment by lifra-esquel** [comment]
Yes.

**Comment by PatrykPorabik** [comment]
It's something strange. I added to my mongod.cfg file this part:
net:
  port: 8080
Then restarted MongoDB. After this steps I'm able to connect to database from Robomongo and also I'm able to install GrandNode on new port. Did you modify your config file?

**Comment by lifra-esquel** [comment]
I run the command "mongod --port 27018 --dbpath C:\XXXX" to start the mongodb. 
Actually, I suspect that there may be some issue on Dependency Resolving logic. As when I debug the code, the IMongoClient has host= 127.0.0.1 and port=27017, which is incorrect.

**Comment by PatrykPorabik** [comment]
Better solution is to change config file. You will change port for MongoDB as a service, not only for one-time inclusion. It is possible to connect with different port, as I tested and installed it few moments ago.

**Comment by PatrykPorabik** [comment]
I also checked your way to connect with database. I turned off MongoDB Service (it's necessary when you run command which you mentioned), then I run command "mongod --port 8080 --dbpath C:\xxx". And GrandNode had been successfully installed.

**Comment by lifra-esquel** [comment]
Anyway, I was used the Grandnode 3.80 which do have this problem. 
But when I try to use Grandnode 3.90, it got the error. 
![grandnode_error](https://cloud.githubusercontent.com/assets/26396884/24794375/f095606c-1bb7-11e7-826c-70822d9b9478.jpg)

**Comment by PatrykPorabik** [comment]
I also tried with port 27018 and GrandNode is throwing this error. So please use different port than default ports of MongoDB.

**Comment by lifra-esquel** [comment]
I tried port 8080 too. It have the same error

**Comment by PatrykPorabik** [comment]
Did you turn off MongoDB Service in Windows Services? If not please do it before running command. Did you try the way with the config file? If you are able to connect with MongoDB clients, you are able to install GrandNode. I did your steps few times and every time i'm able to install GrandNode successfully.

**Comment by lifra-esquel** [comment]
are you using "Connection String" rather than filling in Database Information?
I have tried that it is successful if use "Connection String"

**Comment by PatrykPorabik** [comment]
I'm filling Database Information, so i'm pretty sure it works.
