### ISSUE TITLE
Questions regarding ASP.Net Core 2.0 and compatibility

### ISSUE THREAD

**Issue by JeanCollas** [grandnode/grandnode#137]
I have a website using ASP.NET Core 2.0, and EFCore/Identity on SQL Server.

My questions are:
- Would your solution be compatible with this authentication? (I don't want to duplicate the registering)
- I saw you were planning on moving to .Net Core 2.0 by the end of November (good! :) ), if I opt for your solution now, will the migration to .Net Core framework be compatible with the existing data?
- If I understand well, you don't have (yet) implemented either an app nor API to access from mobile, only the website, am I correct? If so, I may be able to help a bit on that  topic.

I seriously consider your solution, and may give you some help on the development of features, therefore I would really appreciate some insights from your before I jump in! :) 
I can delay the release to end-November if it is better than migrating from full .Net to .Net Core, but I would appreciate knowing it in advance. 

Thanks!

**Comment by PatrykPorabik** [comment]
Hello Jean,

Thanks for reaching us. It's very motivating for us, when we see that somebody is interested in our solution. 

I'm wondering if we are understanding each other well. Our solution is based on ASP.NET MVC, in the newest version (develop branch, which will be released in November) we are using .NET Core 2.0 and MongoDB, non-relational database. We don't use MsSQL anymore, so I wonder if your website will be compatible with GrandNode. Did you check it?

In GrandNode we're using our own authentication. 

In the case of the mobile app. We've released first version of our mobile app - GrandNode. You can check demo "GrandNode" in AppStore or Google Play. 

Best,
Patryk

**Comment by JeanCollas** [comment]
Thanks for your reply.

I hadn't investigated yet the database compatibility, I thought it would not be much work to make it compatible, but now I realize that I may have made a mistake as MongoDB is not relational.

As I need to stick to SQL I guess the changes involved will be a bit complicated :/ 
But if you think the changes are not too large and the structure could fit, I may implement them. 
How would you estimate the work? Could you give me some insights about the storage structure and what should be changed?

Bonus: What are the reasons that made you move to MongoDB?

**Comment by PatrykPorabik** [comment]
In fact, from the beginning we are using MongoDB. To achieve our goals we had to change engine of nopCommerce. We decided to use non-relational database - MongoDB to improve a store performance when the database is exceptionally large. More information you can find here: [www.grandnode.com](www.grandnode.com)

**Comment by brunobertechini** [comment]
@JeanCollas  I believe a custom plugin for authentication (maybe against your identityserver) is not that complicated to build.

Let me know if you need any help;guidance

I am really focused on dotnetcore version of grandnode (customizations and integration with my own erp)

Bruno
