### ISSUE TITLE
Can't make report via selecting orders in section /Admin/Order

### ISSUE THREAD

**Issue by cenga13** [grandnode/grandnode#142]
I have tried to make a report by selecting some orders, and export it to pdf, but I got only last order.

**Comment by PatrykPorabik** [comment]
Hi,

Could you tell us how to reproduce the issue?

Best,
Patryk

**Comment by cenga13** [comment]
For example, I want to make a report for one week, so I have a list of 10 orders, and I click on option Export to PDF(all found). But when I export it to PDF, I got only last order from the list.

**Comment by PatrykPorabik** [comment]
It's weird. I've tried to Print to PDF (all found) orders and it genereted 5 order. (1 order per page). Did you make any source code customization?
