### ISSUE TITLE
4.0.0 - Configure Plugin - StoreScopeConfiguration is calling wrong route

### ISSUE THREAD

**Issue by brunobertechini** [grandnode/grandnode#147]
When using multistore (more than one store created) and trying to configure any plugin (for example facebook authentication), the action is being redirected to plugin's controller rather than to CommonController.

Example:

a) Create more than one store to allow configuration to show the combobox for each store.
b) go to Configuration \ Local Plugins
c) Locate Facebook Authentication plugin and click configure
d) Select one store from the dropdown

**The browser tries to go to (v4.0.0)**
http://localhost:16592/admin/facebookauthentication/changestorescopeconfiguration?storeid=59eba48f46af8b12687ed896&returnurl=%2fadmin%2ffacebookauthentication%2fconfigure

Instead of calling the action callback and stays at the same page

Bruno

**Comment by KrzysztofPajak** [comment]
Thank you for reporting issue.
Fixed [https://github.com/grandnode/grandnode/commit/7690c408c70bb71365063910a4b7e58cedae0562]
