### ISSUE TITLE
Real product kit with overridable price

### ISSUE THREAD

**Issue by esbee** [grandnode/grandnode#177]
It would be great to be able to create real product kits with overridable prices as follows:

PRODUCT KIT 1 Price $230.00 instead of $270.00 (1x100 + 3x50 + 2x10)
- 1 unit of PRODUCT3 at $100.00 each
- 3 units of PRODUCT5 at $50.00 each
- 2 unit of PRODUCT7 at $10.00 each

**Comment by PatrykPorabik** [comment]
Thanks for the idea. We added it to our road map.

**Comment by esbee** [comment]
Awesome Patryk, thanks a lot!!!
