### ISSUE TITLE
Camel-case content folder

### ISSUE THREAD

**Issue by behzad888** [grandnode/grandnode#178]
I've an error with  `wwwroot/Content`, `wwwroot/Content/Images`, `wwwroot/Content/Images/Thumbs` and `wwwroot/Scripts` directories pascal case, although, in the code used camel-case.

**Comment by PatrykPorabik** [comment]
Can you tell which error do you have? Or how we can reproduce the issue?

**Comment by behzad888** [comment]
When I use hard reload or clear cache, I will have an error as CSS files not found, Although everything is ok at the first time.

**Comment by PatrykPorabik** [comment]
@behzad888, do you have this error on Windows server?

**Comment by behzad888** [comment]
No, I don't. I have this error on Ubuntu Server 16.04.

**Comment by PatrykPorabik** [comment]
Thanks for reporting, I will inform you about progress.

**Comment by PatrykPorabik** [comment]
@behzad888 we've fixed this issue.

**Comment by behzad888** [comment]
@PatrykPorabik Thanks you
