### ISSUE TITLE
Convert BaseEntity to Generic type BaseEntity<Key> and Repository<Entity> to Repository<Entity, Key>

### ISSUE THREAD

**Issue by a-patel** [grandnode/grandnode#188]
Currently, grandnode does not support primary key type (e.g. Guid, Short, long) other than int.

BaseEntity, IRepository (EfRepository) should be changed. Both should support any type of primary key.

Note: It will also affect to UrlRecord and other tables shared by all entities.

**Comment by a-patel** [comment]
I really like the @grandnode solution.
Asp.Net Core (2.x) and MongoDB both are very nice.

**Comment by PatrykPorabik** [comment]
@a-patel Primary key type is a string, not int.

**Comment by a-patel** [comment]
@PatrykPorabik 
Mistaken, Primary key is string.
But my question is, what if we want to use other than string as a primary key?
(for some entity PK is short, int, Guid, Long, string etc.)

**Comment by a-patel** [comment]
@PatrykPorabik 
any update?

**Comment by PatrykPorabik** [comment]
@a-patel Unfortunately we won't change it. Primery key type will be a string, as it is now.

**Comment by a-patel** [comment]
@PatrykPorabik 
thanks for your help.
