### ISSUE TITLE
Unable to load GDIPlus on Mac

### ISSUE THREAD

**Issue by thaoula** [grandnode/grandnode#191]
Hi Guys,

It seems the no-source package is missing GDIPlus libraries. 

An stating GDIPlus could not be initialised is raised in the setup screen.

Extracting the contents of runtime.osx.10.10-x64.CoreCompat.System.Drawing nuget package fixes the issue.

Regards,
Tarek

**Comment by PatrykPorabik** [comment]
@thaoula 

Hello,

Which version of GrandNode do you try to install?

Best,
Patryk

**Comment by thaoula** [comment]
Hi @PatrykPorabik,

GrandNode-Core-4.00-NoSource.web.zip from the releases page.

Regards,
Tarek

**Comment by KrzysztofPajak** [comment]
Hi,
MacOS
brew install mono-libgdiplus

After installing the Mono MDK, Copy Mono MDK Files:

/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/libgdiplus.0.dylib
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/libgdiplus.0.dylib.dSYM
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/libgdiplus.dylib
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/libgdiplus.la
And paste them to: /usr/local/lib
