### ISSUE TITLE
HTTP Error 500.19 - Internal Server Error

### ISSUE THREAD

**Issue by marcelowu** [grandnode/grandnode#192]
HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.

Error Code | 0x80070021
-- | --
This configuration section cannot be used at this path. This happens when the section is locked at a parent level. Locking is either by default (overrideModeDefault="Deny"), or set explicitly by a location tag with overrideMode="Deny" or the legacy allowOverride="false".

**Comment by PatrykPorabik** [comment]
@marcelowu Could you describe more this error?

**Comment by wubuyun** [comment]
I can use version ASP.NET Core 1.0.1  ?

**Comment by PatrykPorabik** [comment]
@wubuyun GrandNode supports ASP.NET Core 2.0.
