### ISSUE TITLE
jquery not loading or Theme DefaultClean

### ISSUE THREAD

**Issue by agentelinux** [grandnode/grandnode#252]
Hi
I am testing deploy GrandNode in Alibaba Cloud but failure.

Not loading Theme DefaultClean and Jquery.

![image](https://user-images.githubusercontent.com/718595/40283293-6954d84e-5c52-11e8-983b-c2cf82d30146.png)

tks
Krishna

**Comment by PatrykPorabik** [comment]
Which version of GrandNode did you try to deploy?

**Comment by agentelinux** [comment]
Hi Patryk,

4.1 docker, 4.1 without source code, and developer docker.

Tks


Em seg, 21 de mai de 2018 02:50, Patryk Porabik <notifications@github.com>
escreveu:

**Comment by PatrykPorabik** [comment]
And did you restart the application after installation?

**Comment by agentelinux** [comment]
But I reinstall again, again.

**Comment by PatrykPorabik** [comment]
If you are using Linux, it's necessary to restart application after successful installation. Reinstallation doesn't work in this case.

**Comment by agentelinux** [comment]
I look this template Views/Shared/*
.cshtml and no exist include for jquery.

**Comment by agentelinux** [comment]
Okay, I try and return feedback.
Very tks.

**Comment by agentelinux** [comment]
Patryk,
Really....
I try 

1. re-install
2. docker stop
3. docker start
4. Browser
5. Success!!!

Thanks!!
[]s
Krishna
