### ISSUE TITLE
4.20 - Add titles in admin panel for push notifications pages

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#267]
Add titles in admin panel for push notifications pages

**Comment by TTomu** [comment]
[f73af8f](https://github.com/grandnode/grandnode/commit/fc2272e55a32866e7082d813ee8506f270cba656)
[4a492b6](https://github.com/grandnode/grandnode/commit/4a492b6de3de4cdf4a039a9c00bdfc95d115115c)
[d128c69](https://github.com/grandnode/grandnode/commit/d128c69feae4e99d8fbcb96493dbd0c1d1182871)
