### ISSUE TITLE
Promotions > Push Notifications Not Found

### ISSUE THREAD

**Issue by hassanelsherbiny** [grandnode/grandnode#313]
when you try to navigate to 
Promotions > Push Notifications it opens this link "/Admin/PushNotifications/List"
displaying 404 error page not found i have searched the view folder i didn't find any view for list and there is not action for List in Admin/PushNotificationsController
grandNode Version : 4.1

**Comment by PatrykPorabik** [comment]
Hi,

Push notifications will be implemented in GrandNode 4.20.

Best,
Patryk
