### ISSUE TITLE
4.30 - Add publish setting to topic

### ISSUE THREAD

**Issue by TTomu** [grandnode/grandnode#317]
Add publish setting to topic

**Comment by dborovsky** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/3728303/63403496-290c1f00-c3e8-11e9-847c-acf2e895b914.png)

@PatrykPorabik  We have publish setting to topic. What do you mean to add?

**Comment by PatrykPorabik** [comment]
Hi Dmitriy,

I thought about "Published" setting. The same as you can find for example on product edit page or news creation page. It specify if the item should be published in the public store or not. Imagine that you are working on particular topic and want to check how it looks, but keep it private, accessible only by admin. You can do it with Published setting. You will figure out, what's going on with this setting.

**Comment by dborovsky** [comment]
Good, All clear now
