### ISSUE TITLE
Implement the ML.net library

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#331]
Implement the ML.net library

**Comment by KrzysztofPajak** [comment]
Will be available as paid plugin.

**Comment by scharada** [comment]
hi. can we have an idea about what features will be implemented in the plugin and will it be able to do ?

**Comment by KrzysztofPajak** [comment]
Hi,
Our idea is implement such features:
1. Cross sales - if you buy product X you can also interest product Y - automatically assign by ml.net
2. Alternative products as a related product - automatically assign by ml.net
3. Maybe own chatbot or integration with existing?
4. Improved product Search - implementing ranking product
5. Improving customer segmentation - by customer tags, roles
6. Recomended product per customer - automatically assign by ml.net
7. Predicting product demand - recomendation of stock inventory
If you have any other idea please share it.

Regards
Krzysztof
