### ISSUE TITLE
Add "Show/Hide Filters" button on Orders, Customers, Add product popups

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#336]
Add "Show/Hide Filters" button on Orders, Customers, Add product popups

**Comment by TTomu** [comment]
[2679ad4](https://github.com/grandnode/grandnode/commit/2679ad4541b553e5726f34813e8c98271aeecafc)

[ebf8909](https://github.com/grandnode/grandnode/commit/ebf8909364be2b40647cf826ed60ab952d4ad7dc)
