### ISSUE TITLE
Possibility to create sub accounts for customers

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#345]
Possibility to create sub accounts for customers

**Comment by dborovsky** [comment]
Can you provide more detail about sub accounts. I can help you. Or tell me which issues is more important now? I mean not onlly bugs. maybe features too.

**Comment by KrzysztofPajak** [comment]
Please check this issue: #623

**Comment by Leonardo-Ferreira** [comment]
Can you provide further details on this one? Will the user create such accounts himself? if not, who will? How will they be managed? Can these be deleted?

Is this a scenario where a parent will create accounts for their family?
