### ISSUE TITLE
ERROR TO DEPLOY (PUBLISH) GRANDNODE UBUNTU 18.04

### ISSUE THREAD

**Issue by wubuyun** [grandnode/grandnode#356]
ERROR TO DEPLOY (PUBLISH) GRANDNODE UBUNTU 18.04
root@ubuntu:/var/www/html/gn# sudo dotnet publish Grand.Web –c Release –o /var/www/html/GrandNode
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1008: Only one project can be specified.
Switch: –c

**Comment by PatrykPorabik** [comment]
It's weird, but please enter this command manually, after copying I got this error. It was fine when I wrote it by myself.

**Comment by wubuyun** [comment]
Thanks..

root@ubuntu:/var/www/html/gn# sudo dotnet publish Grand.Web -c Release -o /var/w                                                               ww/html/GrandNode
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for /var/www/html/gn/Grand.Core/Grand.Core.csproj...
  Restoring packages for /var/www/html/gn/Grand.Services/Grand.Services.csproj...
  Restoring packages for /var/www/html/gn/Grand.Data/Grand.Data.csproj...
  Restoring packages for /var/www/html/gn/Grand.Framework/Grand.Framework.csproj...
  Generating MSBuild file /var/www/html/gn/Grand.Services/obj/Grand.Services.csproj.nuget.g.props.
  Generating MSBuild file /var/www/html/gn/Grand.Data/obj/Grand.Data.csproj.nuget.g.props.
  Generating MSBuild file /var/www/html/gn/Grand.Core/obj/Grand.Core.csproj.nuget.g.props.
  Generating MSBuild file /var/www/html/gn/Grand.Framework/obj/Grand.Framework.csproj.nuget.g.props.
  Restore completed in 13.73 sec for /var/www/html/gn/Grand.Framework/Grand.Framework.csproj.
  Restore completed in 13.7 sec for /var/www/html/gn/Grand.Core/Grand.Core.csproj.
  Restore completed in 13.7 sec for /var/www/html/gn/Grand.Data/Grand.Data.csproj.
  Restore completed in 13.71 sec for /var/www/html/gn/Grand.Services/Grand.Services.csproj.
  Restoring packages for /var/www/html/gn/Grand.Web/Grand.Web.csproj...
  Generating MSBuild file /var/www/html/gn/Grand.Web/obj/Grand.Web.csproj.nuget.g.props.
  Restore completed in 511.55 ms for /var/www/html/gn/Grand.Web/Grand.Web.csproj.
  Grand.Core -> /var/www/html/gn/Grand.Core/bin/Release/netcoreapp2.1/Grand.Core.dll
  Grand.Data -> /var/www/html/gn/Grand.Data/bin/Release/netcoreapp2.1/Grand.Data.dll
  Grand.Services -> /var/www/html/gn/Grand.Services/bin/Release/netcoreapp2.1/Grand.Services.dll
  Grand.Framework -> /var/www/html/gn/Grand.Framework/bin/Release/netcoreapp2.1/Grand.Framework.dll
  Grand.Web -> /var/www/html/gn/Grand.Web/bin/Release/netcoreapp2.1/Grand.Web.dll
  Grand.Web -> /var/www/html/GrandNode/
root@ubuntu:/var/www/html/gn#

**Comment by wubuyun** [comment]
installed, it returns to the installation page..
![capturar1](https://user-images.githubusercontent.com/35350235/45772910-515f2c80-bc1f-11e8-9abf-eb3c64ee3f49.PNG)

**Comment by PatrykPorabik** [comment]
After successfull installation you need to restart the application. After that you will see the homepage of your store.

**Comment by wubuyun** [comment]
thanks
