### ISSUE TITLE
SAST and Insecure Random Number Generator

### ISSUE THREAD

**Issue by dominioncommerce** [grandnode/grandnode#362]
PumaScan, a Static Application Security Testing tool for .NET, has flagged some high and medium security risks.   Some may be false positives, but one issue stands out - Insecure Random Number Generator.  

Please see the following issue reported on for 4.20.01:

SEC0115: Insecure Random Number Generator
System.Random is a statistical random number generator that does not generate sufficiently random values for use in a security context. Generate values used in a security context (e.g., encryption keys, initialization vectors, random passwords, authentication tokens) using the System.Security.Cryptography.RNGCryptoServiceProvider. 

Code References
Grand.Core.csproj | CommonHelper.cs:
72: var random = new Random();
Grand.Core.csproj | CommonHelper.cs:
89: return new Random(BitConverter.ToInt32(randomNumberBuffer, 0)).Next(min, max);
Grand.Services.csproj | Installation\CodeFirstInstallationService.cs:
9671: var random = new Random();

For more information, see https://pumascan.com/rules/#sec0115-insecure-random-number-generator

Please advise.  I'm not sure what such a change would impact but recommend remediation over time.

Thanks,
Matt

**Comment by KrzysztofPajak** [comment]
Random method used in CodeFirstInstallationService 
is used only for generate sample data. 
Other usage was changed. 
Thank you,
Krzysztof
