### ISSUE TITLE
lets ssl error in store

### ISSUE THREAD

**Issue by wubuyun** [grandnode/grandnode#366]
ubuntu 18.04
lets ssl error in front- store
end-store admin is ok, some Admin/Product/List is error

**Comment by PatrykPorabik** [comment]
Can you provide more details? How can we reproduce this issue?

**Comment by wubuyun** [comment]
A bad HTTP response code (404) was received when fetching the script.

Failed to load resource: net::ERR_INVALID_RESPONSE

15Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure image '<URL>'. This content should also be served over HTTPS.

'http://s7.addthis.com/js/250/addthis_widget.js'. This content should also be served over HTTPS.

**Comment by PatrykPorabik** [comment]
Just change the http into https in addthis widget. You can do it in **Admin panel -> Configuration -> Settings -> Catalog settings -> Sharing.** If it's not possible, remove it, it will solve the problem. It's not related with GrandNode, AddThis Widget is a third part tool.
