### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by wubuyun** [grandnode/grandnode#375]
Mixed Content: The page at 'https://www.nihaomodas.com.br/25-virtual-gift-card' was loaded over HTTPS, but requested an insecure favicon 'http://www.nihaomodas.com.br/favicon.ico'. This request has been blocked; the content must be served over HTTPS.

Mixed Content: The page at 'https://www.nihaomodas.com.br/cart/' was loaded over HTTPS, but requested an insecure favicon 'http://www.nihaomodas.com.br/favicon.ico'. This request has been blocked; the content must be served over HTTPS.

**Comment by PatrykPorabik** [comment]
It's problem related with nginx configuration, I guess. Did you set a proxy_set_header X-Forwarded-Proto $scheme;?

**Comment by wubuyun** [comment]
yes, and admin is ok , store only error

**Comment by PatrykPorabik** [comment]
Did you modify also the appsettings.json file? You should change the UseHttpXForwardedProto to True (it's line 5 in appsettings.json)?

**Comment by wubuyun** [comment]
solved Thanks..
