### ISSUE TITLE
Redesign administration panel theme

### ISSUE THREAD

**Issue by scharada** [grandnode/grandnode#392]
have you tried applying/using Metronic theme for admin ?

**Comment by PatrykPorabik** [comment]
Hello,

We are using Metronic theme, but maybe the older version.

**Comment by scharada** [comment]
if i used a newer version , would it work ? are there a lot of incompatibilities to fix ?

**Comment by scharada** [comment]
oh that would be awesome Patryk.

**Comment by scharada** [comment]
and if i may suggest, remove those layouts and themes from the admin area. i don't think they are used by anybody. having a beautiful admin theme based on metronic is more then enough and can be customized if needed.
splitting css and js over multiple files in different locations to customize it makes things much harder ... 
i have seen a case on another system lately where hundreds of users are struggling to customize the theme because of the integration in the admin area... try to avoid it and stick to the original theme as much as you can. it makes people's life easier.   thanks.

**Comment by PatrykPorabik** [comment]
It's impossible to implement, due to changes in the Metronic license. We decided to change theme admin area theme.
