### ISSUE TITLE
How use RedisCacheManager in web.config

### ISSUE THREAD

**Issue by agentelinux** [grandnode/grandnode#415]
Hi Guys,

I not found example to web.config with RedisCacheManager.
Any tips?

Very tks.
[]s
Krishna

**Comment by PatrykPorabik** [comment]
Hi,
RedisCaching can be configured in appsettings.json file, not in web.config. Here is an example:
https://github.com/grandnode/grandnode/blob/develop/Grand.Web/App_Data/appsettings.json#L63

Best,
Patryk

**Comment by agentelinux** [comment]
Fantastic.

**Comment by agentelinux** [comment]
Tips
https://stackexchange.github.io/StackExchange.Redis/Configuration.html
Redis for not Azure:
* add RedisCachingConnectionString with abortConnect=true
