### ISSUE TITLE
IndexOutOfRange Exception on virtually all page loads 

### ISSUE THREAD

**Issue by wwrighter** [grandnode/grandnode#423]
**Describe the bug**
An IndexOutOfRange exception is thrown on virtually every loaded page via GrandNode.  The cause appears to be an empty string that is processed with the TypeConverter.IsValid method.  The exception seems to generate unnecessary overhead for every page load.  To easily identify the call stack set up Exception Settings in VS to break on System.IndexOutOfRangeException.

Looks to be caused by DateOfBirthMinimumAge (of type Nullable<Int>) having an empty string ("") which is processed in GrandNode.Services/Configuration/SettingService.cs +356 via the call to IsValid, which in turn catches an exception from ConvertFrom.

**To Reproduce**
1. Setup and build current GrandNode source (time of writing: 4.40) in Visual Studio 2017 15.9.4 with dotnet 2.2 sdk and mongo 4.05 all setup and configured.
2. Uncheck "Just My Code" via VS Debug > Options > Debugging > General
3. Run Grand.Web in Release mode using IIS Express, go through initial configuration / data insertion in mongodb.
4. Monitor the Event window paying mind to Exceptions on all page loads

**Expected behavior**
Expect the empty string to be handled properly in this case and properly converted to a nullable int.  No exceptions to be raised on page load due to an empty string in the settings of DateOfBirthMinimumAge.

**Desktop (please complete the following information):**
 - Browser : Edge in this case

**Just a few random thoughts**
Thought of potentially opening up a PR with a custom typeconverter via AutoMapper, or even just a simple check on the string for nullorwhitespace and returning the default(int?) but wanted to get some feedback on potential solutions and the state of LoadSettings as it sits.

**Comment by KrzysztofPajak** [comment]
Hi,
Thanks for report a bug.
In this case maybe good solution will be change line:
https://github.com/grandnode/grandnode/blob/166de496ef5fcf1ecfc2a0f39ffc0f857db7d097/Grand.Services/Configuration/SettingService.cs#L350
if (setting == null) 
to
if (setting == null || setting.Length == 0)

Best Regards
Krzysztof
