### ISSUE TITLE
GrandNode and Single Sign-On Functionality

### ISSUE THREAD

**Issue by senorpinatta** [grandnode/grandnode#436]
Hello there,

Around the same time that I discovered GrandNode, I have been learning about Single Sign-On functionality with IdentityServer4.

I would like to implement SSO functionality within a GrandNode project so that users can perhaps interact through Facebook for example.

For me the project is quite large and I'm unsure where I would place the code for that. And while I was exploring the project I've seen some files referring to JWT and External Authentication. This makes me think that GrandNode might already support this function.

I'm wondering if some more explanation can be provided about how to do this, and how it works.

Docs I have consulted are:
http://docs.grandnode.com/architecture-of-grandnode
http://docs.grandnode.com/web-api
http://docs.grandnode.com/external-authentication

Thanks for your time

**Comment by PatrykPorabik** [comment]
GrandNode doesn't have implemented Single Sign-On functionality.  GrandNode has implemented External Authentication with Facebook out of the box, as a plugin or Google, as a plugin downloadable from our marketplace. JWT which you mentioned is related with Web API, which will be added to the GrandNode 4.40 version in the nearest future.

**Comment by senorpinatta** [comment]
Thanks for your quick response.
