### ISSUE TITLE
when i call api return page not found?

### ISSUE THREAD

**Issue by hussein7** [grandnode/grandnode#439]

**Comment by KrzysztofPajak** [comment]
Please check documentation http://docs.grandnode.com/web-api

**Comment by hussein7** [comment]
when create token raise exception 

`An exception of type 'System.FormatException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.'
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)`

**Comment by KrzysztofPajak** [comment]
Please read carefully documentation.

**Comment by hussein7** [comment]
thanks man it working well.can i do customization based on my project
