### ISSUE TITLE
Discount Price Plugin Quantity

### ISSUE THREAD

**Issue by ndfullard** [grandnode/grandnode#443]
Hi

Currently we calculate a product discount using a discount plugin, and one of the values we require to calculate the discount is the quantity being ordered.

Would it be possible to add the order quantity to the parameters being passed to the DiscountAmount method of the plugin.

We have modified the source core code to include this and we re-implement this change to the core source code with each release, but I'm sure others may have a use for it.

Regards,
Nic

![quantity](https://user-images.githubusercontent.com/41153824/51684422-ac9d9300-1ff4-11e9-965c-5d939e94de59.png)
.

**Comment by KrzysztofPajak** [comment]
Hi
Could you explain why do you need quantity ?
Do you want create discount amount based on quantity (of course, quantity in the cart) ?
Regards
Krzysztof

**Comment by ndfullard** [comment]
Hi Krzysztof

Thanks for getting back to me, In our particular case we use the plugin
functionality to call an external web service on our ERP system which
calculates and returns the discount, the web service requires the customer
code, product sku, and the order quantity to calculate the discount, but
any number of other scenarios might require the order quantity to perform a
custom discount calculation.

Regards
Nic
