### ISSUE TITLE
Add Elastic search to cms

### ISSUE THREAD

**Issue by Hamidnch** [grandnode/grandnode#445]
Please add elastic search technique for imporving search in store.

Thanks for your nice cms.

**Comment by Hamidnch** [comment]
Please add elastic search technique for imporving search in store.

**Comment by PatrykPorabik** [comment]
Hi,
We want to implement a new search engine library in 4.50 version. We will consider it.

**Comment by Hamidnch** [comment]
Hi dear.


> Hi,
> We want to implement a new search engine library in 4.50 version. We will consider it.

Is it bettar then Elastic Search In terms of speed؟
Thanks.

**Comment by PatrykPorabik** [comment]
What is better? We have not picked one yet.

**Comment by Hamidnch** [comment]
> 
> 
> What is better? We have not picked one yet.

Hi.
Ok. Thanks.

**Comment by PatrykPorabik** [comment]
Main thread - #437
