### ISSUE TITLE
Admin View: Moment.js - deprecation warning for moment().subtract

### ISSUE THREAD

**Issue by wwrighter** [grandnode/grandnode#448]
Minor: Figured I would create the issue for tracking purposes only.  

**Describe the bug**
Minor syntax issue with Moment.js when viewing the admin page.  (deprecated use of moment().subtract() warning)

**To Reproduce**
1. Go to 'Admin Page' with Developer Console (i.e. F12 running)
3. Check out the console warning
4. See console warning: **moment.min.js:6 Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period).**

**Additional context**
Seems to be a simple rearrangement of the arguments to subtract: 
https://github.com/grandnode/grandnode/blob/d29c5f8d21930f51f775ced345b5b74914b025a8/Grand.Web/Areas/Admin/Views/Home/Index.cshtml#L266-L270

**Comment by PatrykPorabik** [comment]
It's just the warning. I think it will be fixed after the admin panel template upgrade to the newest version.
