### ISSUE TITLE
Wrong autogenerated robots.txt

### ISSUE THREAD

**Issue by andreyshade** [grandnode/grandnode#450]
**Describe the bug**
When I check my site using Chrome developer tool I get error: 

> If your robots.txt file is malformed, crawlers may not be able to understand how you want your website to be crawled or indexed.

**To Reproduce**
1. Open your page in Chrome browser
2. Open developer tools tab, choose Audits tab and perform the audit
4. You can see common web app issues and recommendations

**Comment by wwrighter** [comment]
@andreyshade - Is this on a stock install of GrandNode?  Was unable to reproduce on GrandNode 4.30, but seeing as though robots.txt is generated along the way, maybe there was some issue or sequence of steps that led to it.  

If you run it your robots.txt through the robots.txt Tester via Google's Search Console does it narrow down the errors in the robots.txt?  If so, maybe it would be a good place to start - to determine how that problem ended up in there.

**Comment by PatrykPorabik** [comment]
@andreyshade I made steps which you described and I got the same information, but it's only information. Above it you have a note that "robots.txt" is valid. It's just a exaplanation, what will happen if you don't have valid robots.txt file. See the attached image.

![image](https://user-images.githubusercontent.com/16773025/52194057-7234c100-2852-11e9-9186-ce7ebe1c2ca7.png)

**Comment by andreyshade** [comment]
It happened when I use many languages on site
[http://prntscr.com/mgbdzu](http://prntscr.com/mgbdzu)

**Comment by PatrykPorabik** [comment]
We got it. We will investigate it.

**Comment by PatrykPorabik** [comment]
@andreyshade Issue has been fixed. Please look at the commit above.
