### ISSUE TITLE
HTTP Error 500 when submit POST request to /api/token/create

### ISSUE THREAD

**Issue by bzxnvpr** [grandnode/grandnode#451]
I have followed the statement the enable API in appsetting.json as below. Please help to check. Thanks

p.s. I am using docker for grandnode 4.4 and mongodb.

> "Api": {
    "Enabled": true,
    "SecretKey": "grandnode1",
    "ValidateIssuer": false,
    "ValidIssuer": "",
    "ValidateAudience": false,
    "ValidAudience": "",
    "ValidateLifetime": true,
    "ValidateIssuerSigningKey": true,
    "ExpiryInMinutes": 1440,
    //generate system model
    "SystemModel":  true
  }

Error Msg:

> ArgumentOutOfRangeException: IDX10603: Decryption failed. Keys tried: '[PII is hidden]'.
Exceptions caught:
'[PII is hidden]'.
token: '[PII is hidden]'
Parameter name: KeySize

> Grand.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions+<>c.<UseGrandExceptionHandler>b__1_1(HttpContext context) in ApplicationBuilderExtensions.cs, line 90

**Comment by wwrighter** [comment]
You're absolutely right.  The "problem" is exactly as you reported.  Specifically "IDX10603: The algorithm: 'HS256' requires the SecurityKey.KeySize to be greater than '128' bits. KeySize reported: 'XX'. Parameter name: key.KeySize" ; where XX is respective of the number of bits representing your original "short" password you had in your appsettings.

https://github.com/grandnode/grandnode/blob/8280c8cc58ca6d8b3ab9ab10090f3712732fb050/Grand.Api/Jwt/JwtTokenBuilder.cs#L93


**If you extend the length of the password you created in appsettings.json .  You can avoid this issue.**

**Comment by bzxnvpr** [comment]
many thanks for help!
