### ISSUE TITLE
LocalStringResource values not removed from MongoDB when plugin is uninstalled

### ISSUE THREAD

**Issue by shivaRamdeen** [grandnode/grandnode#453]
**Describe the bug**
When a plugin is uninstalled from the system the Locale String Resource entries in mongodb are not removed (Release-4.30) for the uninstalled plugin. On the Admin panel the uninstall process reports as a success.

**To Reproduce**
1. Clone Release-4.30
2. Run on IIS Express using visual studio
3. Follow installation procedure on screen when prompted (use sample data when prompted)
4. Once GrandNode is installed, login to the admin panel
5. Goto Configuration->Local Plugins
6. Uninstall Fixed Tax Rate Provider Plugin
7. Open the db used in grandnode in MongoDB Compass
8. Navigate to the LocaleStringResource collection
9 Explore/Query the data and notice that the string resources for the plugin are not removed

**Expected behavior**
When the plugin is uninstalled, all LocaleStringResources should be removed from the DB. This is most needed during development of plugins

**Screenshots**
**Plugin Uninstalled**
![image](https://user-images.githubusercontent.com/14797072/52537965-1a5ef400-2d43-11e9-926c-64438a311ea6.png)

**Values Still Persisted in DB**
![image](https://user-images.githubusercontent.com/14797072/52537961-09ae7e00-2d43-11e9-98a1-a2cf8ecad8e3.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - IDE: VS 2017 Community
 - Windows 10 Home
 - IIS Express

**Comment by PatrykPorabik** [comment]
Hello,
This problem is fixed in the newest version of GrandNode, currently on the develop branch.
