### ISSUE TITLE
'Contact us' bug in email body

### ISSUE THREAD

**Issue by andreyshade** [grandnode/grandnode#454]
**Describe the bug**
Email body is not interpolated. Currenct view:

> From {ContactUs.SenderName} - {ContactUs.SenderEmail} {ContactUs.Body}

**To Reproduce**
1. Send request via "Contact us" form
2. Open received email
3. See error

**Expected behavior**
A email body must be interpolated

**Comment by PatrykPorabik** [comment]
Which version of GrandNode are you using? I'm not able to simulate this problem on our demo in 4.40 version.

**Comment by andreyshade** [comment]
Latest develop

**Comment by PatrykPorabik** [comment]
It's ok. Please change the message tokens - tokens should have {{ }} instead of { }.
