### ISSUE TITLE
Latest Visual Studio crashes opening the solution

### ISSUE THREAD

**Issue by dolphinsd** [grandnode/grandnode#457]
I tried to open your  solution in the latest visual studio and it crashes my computer with bluescreen every time.

1. Latest visual studio version 15.9.7
2. Get the latest code
3. Try to open solution file.

Sad msft bluescreen face.

**Comment by wwrighter** [comment]
Sounds like a device driver, update, MS issue.  Have you tried opening up a support issue with MS? Any other solutions cause this? 

I've loaded and run this solution with the lasted MS Visual Studio without issue.

**Comment by KrzysztofPajak** [comment]
Hi,
Please try to apply some tips to improve performance of Visual Studio
More info you can find here:
[https://docs.microsoft.com/en-US/visualstudio/ide/visual-studio-performance-tips-and-tricks?view=vs-2017]
