### ISSUE TITLE
Developer Help

### ISSUE THREAD

**Issue by mmakdessii** [grandnode/grandnode#464]
As a developer, what do I need to know in order to start working on GrandNode?
As also a user, what should I know. 
I want to know what to learn in order to run grandnode and be able to customize it accordingly so I can open my business.

**Comment by PatrykPorabik** [comment]
It's necessary to have a knowledge about C#, .NET, MongoDB. GrandNode uses also HTML, CSS, JavaScript. We based our themes on Bootstrap, so it's also good to know it a little. In the case of customization, mostly it will be related with the front end customization, so the HTML, CSS, JavaScript knowledge will be necessary.
