### ISSUE TITLE
Flag text translation

### ISSUE THREAD

**Issue by TTomu** [grandnode/grandnode#468]
Flag filed on category should be translated

**Comment by dborovsky** [comment]
@PatrykPorabik @TTomu do you mean translate dynamic content from database?

http://prntscr.com/okdebn

**Comment by PatrykPorabik** [comment]
Can you check for example category name? It's localizable. You can change the tab with language and provide different translation. We want something similar with Flag text. Add this boxes with languages and add possibility to provide different flag name for different languages.

**Comment by dborovsky** [comment]
yes. I see. i will fix
