### ISSUE TITLE
Azure App Service Docker image - Installation issue

### ISSUE THREAD

**Issue by kishoresahas** [grandnode/grandnode#469]
Azure App Service Docker image - Installation issue
While installing grand node in Azure App Service Docker image. The installation is not getting completed.

1. Go to Azure
2. Click on new App service 
3. Select Docker Image
4. Go to Url
5. Enter the details and client on Install
6. The DB is getting created
7. But after that get a message "Application has been installed successfully, please restart application."
8. Never goes to Home Page

**Expected behavior**
After installation navigate to Home Page.

**Screenshots**
![image](https://user-images.githubusercontent.com/5591712/53731797-e68a7080-3ea1-11e9-82a2-1d1e7763943d.png)

![image](https://user-images.githubusercontent.com/5591712/53732228-3f0e3d80-3ea3-11e9-993f-84445d3e4408.png)

**Findings**
Docker is not persisting the settings file like "..\App_Data\appsettings.json"

**Comment by PatrykPorabik** [comment]
Did you restart the application? After restarting, please go to your homepage URL (remove the /install part from URL address)

**Comment by kishoresahas** [comment]
Yes restarted the application, after restarting tried with removing /install. 
But it still redirects automatically back to /install.

**Comment by kishoresahas** [comment]
Is there a possibility that this could be a Azure container issue ?

**Comment by PatrykPorabik** [comment]
Did you check the database? Can you connect to it and check if it contains tables from GrandNode or not?

**Comment by kishoresahas** [comment]
Yes there are 115 tables created in Database.

**Comment by kishoresahas** [comment]
One more findings, I created a sample project to simulate the same, with App_Data and file operations. It works perfectly.

**Comment by kishoresahas** [comment]
Found the issue and fixed it, docker container needs to be restarted explicity. 

Also please note App server restart is not enough
https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image
