### ISSUE TITLE
Create more Unit tests

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#472]
Create more Unit tests

**Comment by PatrykPorabik** [comment]
As much as possible :)

**Comment by PatrykPorabik** [comment]
@dborovsky If you have free time, we would love to increase the number of Unit tests in the project. Maybe can you help with that?

**Comment by dborovsky** [comment]
@PatrykPorabik  Yes, I can, but cover whole grandnode solution with unit tests will be hunderts tests. I'll write tests at my discretion.

**Comment by PatrykPorabik** [comment]
@dborovsky just look at the Tests project and just try to extend it according to the existing patterns :) I don't say that you should cover the whole project:)

**Comment by dborovsky** [comment]
yea, I will be. all clear
