### ISSUE TITLE
Add Chinese(Traditional) Language while on installation

### ISSUE THREAD

**Issue by Weidaicheng** [grandnode/grandnode#477]

**Comment by PatrykPorabik** [comment]
@Weidaicheng if we get Chinese language pack with correct translations, we can add it to the project with pleasure.

**Comment by Weidaicheng** [comment]
@PatrykPorabik I can provide a Chinese(Traditional) language pack, and I also found some translation mistakes in Chinese(Simplified), and a css issue which was related to change language in installation page.
You can assign this to me, and I'll do this.

**Comment by PatrykPorabik** [comment]
Sure. That's great! I assigned you. Just send us a pull request after work, we will merge it with the project.
