### ISSUE TITLE
Slider Widget Issues with v4.40

### ISSUE THREAD

**Issue by ndfullard** [grandnode/grandnode#486]
In the PublicInfo.cshtml file of the slider widget, there is an if statement on line 40 where the logic seems to be reversed, if item.Link is empty then it implements href="item.Link", but if item.Link contains a value then the value is ignored. (Image attached.)

Also the wide-img and no-wide-img classes seem to cause the item.Description to appear below the image in white text which cannot be seen, rather then appearing as an overlay on top of the image as before (in v4.30). (I have attached an image where I selected the text so it can be seen.)

Regards,
Nic

![hidden_description](https://user-images.githubusercontent.com/41153824/54180474-6fa63680-44a4-11e9-9a14-63075b989603.PNG)
![reversed_logic](https://user-images.githubusercontent.com/41153824/54180482-73d25400-44a4-11e9-8685-30f27f3b486b.PNG)

**Comment by PatrykPorabik** [comment]
Hello Nic,
Thank you for reporting. To be honest, we wanted to create a setting which specify if slider should be full width or not. We created a draft with that statement, it will be removed and replaced with proper setting, in next version of GrandNode, I suppose.

**Comment by ndfullard** [comment]
Hi Patryk

No problem, thank you for the feedback. I have implemented my own work
around in the mean time, but I look forward to the next version being able
to select full screen or not, specifically in our case we like to use a
full screen slider with the pre-uploaded image and an overlay text set in
the description box, if we could choose for this text to align to the top
of the image that would be awesome as it would allow us to overlay text
with effects across the entire image like you have done in the new 4.40
theme. (currently with the pre-uploaded image the text aligns to the bottom)

Regards,
Nic
