### ISSUE TITLE
Possible Bug in Customer Creation Flow

### ISSUE THREAD

**Issue by senorpinatta** [grandnode/grandnode#494]
I'm not sure if this is a bug or if I'm misunderstanding the operation flow.

When creating a new customer, (/Admin/Customer/Create) after clicking "Save", I am returned to the Customer List screen with 2 messages:

![registration](https://user-images.githubusercontent.com/8880195/54335463-9bb7e800-465b-11e9-9c53-ba46a21b74c2.png)

From what I can tell, the error message is caused because the function ChangePassword is used to assign a password to a Customer, but it is called before the Customer is actually registered.

### Create Customer
![reg](https://user-images.githubusercontent.com/8880195/54335643-357f9500-465c-11e9-9514-295780a60bea.png)

Furthermore, because the password is never 'changed', the customer's password ends up being "" (blank, the base password used in the ChangePasswordRequest function).

### Call to ChangePassword
- attempt to retrieve customer before customer is 'registered'
![ger](https://user-images.githubusercontent.com/8880195/54335749-84c5c580-465c-11e9-8e1d-a1a11236db7b.png)
 
Hope to hear some thoughts on this

**Comment by PatrykPorabik** [comment]
Hi @senorpinatta,
Thanks for reporting. It may be an issue.
