### ISSUE TITLE
How can redirect host IP to domain in Ubuntu? [Help Post]

### ISSUE THREAD

**Issue by rajibdpi** [grandnode/grandnode#500]
How can redirect host IP to a domain in Ubuntu? Actually, how can block direct access to  Grandnode  4.30 using ip?

I'm using 

- apache2

- Mongodb 3.6

- Grangnode 4.30

**Comment by rajibdpi** [comment]
Hello

**Comment by PatrykPorabik** [comment]
Hi,
Sorry for delay, I deleted your newest comment, because it didn't impact on the issue. Did you try to redirect domain to IP in your domain panel? In the case of access block, it's better to ask someone familiar with Apache, because I'm not a specialist in the case of Apache.

**Comment by rajibdpi** [comment]
> Hi,
> Sorry for delay, I deleted your newest comment, because it didn't impact on the issue. Did you try to redirect domain to IP in your domain panel? In the case of access block, it's better to ask someone familiar with Apache, because I'm not a specialist in the case of Apache.

Thank you for your replay. Already solved it by me.
