### ISSUE TITLE
Site crashed when moved to the RTL locale (with HTML minification enabled)

### ISSUE THREAD

**Issue by sergey-messer** [grandnode/grandnode#503]
**Describe the bug**
After change locale to Hebrew demo site crashed

**To Reproduce**
1. Go to 'Admin->Configuration->Languages->Add new'
2. Click on 'Add new '
3. Select language culture, name, flag "Hebrew" and CHECK RTL check box (it is important),  save
4. Go to demo portal and change language to Hebrew, portal is crashed

**Expected behavior**
Interface is in Hebrew localization

**Desktop (please complete the following information):**
 - All Browsers

**Smartphone (please complete the following information):**
 - Device: All devices
 - Browser All browers

**Additional context**

**Comment by PatrykPorabik** [comment]
Hi,
GrandNode doesn't have translated content into Hebrew. So if you change language, you will see only resource strings that are able to translate.

**Comment by sergey-messer** [comment]
It is not related to Hebrew translation. Try to set Right-To-Left check box even to English language and demo site will be crash

**Comment by PatrykPorabik** [comment]
You're right. Thanks for notification, we will investigate it.
