### ISSUE TITLE
Blog post removal, doesn't make the SeName inactive

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#506]
**Describe the bug**
Blog post removal, doesn't make the SeName inactive

**To Reproduce**
1. Go to Admin panel -> Content Management -> Blog -> Blog post
2. Delete one of blog post
3. Go to System -> Search Engine Friendly Names -> Search for deleted blog post
4. As result we will see active SeName, even if it's removed.

**Expected behavior**
SeName marked as Inactive after blog post removal.

**Comment by nazneennahar** [comment]
hey i would like to work on this please
