### ISSUE TITLE
Top "Header Links" menu taking time to load than other elements on page

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#510]
"Top "Header Links" menu taking time to load than other elements on page"

Source: [https://grandnode.com/boards/topic/5ca4c7150a0af1213c36be0b/top-header-links-menu-taking-time-to-load-than-other-elements-on-page](https://grandnode.com/boards/topic/5ca4c7150a0af1213c36be0b/top-header-links-menu-taking-time-to-load-than-other-elements-on-page)

**Comment by PatrykPorabik** [comment]
It was used to prevent showing the material icons description until they are fully loaded.

**Comment by ajaydudy** [comment]
Problem still persists

**Comment by ajaydudy** [comment]
Issue is still there, why not use "fontawesome"?

**Comment by PatrykPorabik** [comment]
It's behavior of material icons. If we won't lazy load the icons, you will see the string with the name of the icon. We will consider to change icons in the future.
