### ISSUE TITLE
Cannot start service mongo: driver failed programming external connectivity on endpoint 

### ISSUE THREAD

**Issue by kishoresahas** [grandnode/grandnode#541]
**Describe the bug**
Getting below error while using the docker-compose. 

E:\docker\grandnode>docker-compose up
Creating network "grandnode_default" with the default driver
Creating grandnode_mongo_1 ... error

ERROR: for grandnode_mongo_1  Cannot start service mongo: driver failed programming external connectivity on endpoint grandnode_mongo_1 (1e54342c07b093e32189aad487927f226b3ed0d1b6bdf7413588377b0e99bc2c): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:27017:tcp:172.20.0.2:27017: input/output error

ERROR: for mongo  Cannot start service mongo: driver failed programming external connectivity on endpoint grandnode_mongo_1 (1e54342c07b093e32189aad487927f226b3ed0d1b6bdf7413588377b0e99bc2c): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:27017:tcp:172.20.0.2:27017: input/output error
ERROR: Encountered errors while bringing up the project.

**To Reproduce**
[docker-compose.zip](https://github.com/grandnode/grandnode/files/3124257/docker-compose.zip)](url)

**Comment by KrzysztofPajak** [comment]
Hi,
This bug is not related with application.

**Comment by kishoresahas** [comment]
Found the issue, it was related docker. need to configure the "Shared Drives" 
For reference : https://token2shell.com/howto/docker/sharing-windows-folders-with-containers
