### ISSUE TITLE
Possible bug or confusing setting

### ISSUE THREAD

**Issue by attila-koteles** [grandnode/grandnode#542]
I am unsure if this the intended setup. It just got me confused so I thought I report it.
There is a setting in [appsettings.json](https://github.com/grandnode/grandnode/blob/develop/Grand.Web/App_Data/appsettings.json#L90) called `UseRequestLocalization`.
If you set it to `true`, my understanding would be that we set the Culture based on the Customer's webrequest (browser/OS setup or ?culture=)

There are other settings to specify our `DefaultRequestCulture` and also `SupportedCultures`. These would be used according to my logic if the `UseReqestLocalization` would be false.

This is the code found in [GrandCommonStartup.cs](https://github.com/grandnode/grandnode/blob/develop/Grand.Framework/Infrastructure/GrandCommonStartup.cs#L119):

            //use request localization
            if (!grandConfig.UseRequestLocalization) // <-- invert if statement?
                application.UseRequestLocalization();
            else

So if `UseRequestLocalization: true` we **don't** use the incoming customer's browser settings, instead we use restricted list of localizations also specified in the settings file.

**To Reproduce**

* Say you have a special browser locale - French, Norwegian
* Set `UseRequestLocalization: true` in appsettings.json
* If you visit the store everything will be set with english locale (using the default settings, SupportedCultures only contains English and Polish locales)

**Expected behavior**

`UseRequestLocalization: true` -> I would expect my locale getting priority. The opposite happens.
It confused me because I actually wanted to restrict the store to a specific culture locale and I had to set this value to `true` in order for it to happen.

**Comment by KrzysztofPajak** [comment]
Hi,
These setting (grandConfig.UseRequestLocalization) could be cause confuse. 
We will fix it. 
About restrict the store to a specific culture locale, please check CultureMiddleware and change for your requiment.
Method UseRequestLocalization is used during the start of the application (not for request).
Best Regards
Krzysztof

**Comment by attila-koteles** [comment]
Thank you for the tip!
You Guys are doing an excellent job by the way! I am very satisfied with Grandnode.
Currently only evaluating, but very good so far.
