### ISSUE TITLE
Product Cache 

### ISSUE THREAD

**Issue by smaddalasweya** [grandnode/grandnode#544]
**Describe the bug**
In product service, we are seeing all products in cache getting removed when Delete Product, Insert Product and UdpateProduct.

I don`t see a reason to remove whole products from cache instead of removing , adding, updating particular product.

**Comment by PatrykPorabik** [comment]
Products may have a many dependencies. For example orders, related products, recommended products, personalized products, etc. It's safier to delete all cache.

**Comment by vachichuong** [comment]
why not change the cache stored in getAll ? , instead of having a dedicated key, use a recursive call and set individually.
So , this way, it won't be deleted all the time and populated again.
