### ISSUE TITLE
Multiple taxes based on customer type

### ISSUE THREAD

**Issue by vachichuong** [grandnode/grandnode#551]
**Is your feature request related to a problem? Please describe.**
In some countries there is an additional tax for wholesale customers for example.

**Describe the solution you'd like**
It would be nice to have a generic enought way add additional taxes based on customer type.

**Comment by PatrykPorabik** [comment]
Thanks for suggestion, but it should be customized in end user store. I don't think so, it will be used globally.

**Comment by vachichuong** [comment]
Yeah, not globally, but in many countries there are multiple taxes, so it would be nice to have it out of the box.
