### ISSUE TITLE
Add search to the Country list

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#553]
Add search to the Country list

**Comment by grantfar** [comment]
I will take this

**Comment by PatrykPorabik** [comment]
Sure! Great! I've assigned you to this task.

**Comment by PatrykPorabik** [comment]
@grantfar you should add a textbox, something similar to this one:
![image](https://user-images.githubusercontent.com/16773025/67069261-cbdce180-f17c-11e9-9e50-a9a978146324.png)
