### ISSUE TITLE
Cannot start GrandNode container on Heroku

### ISSUE THREAD

**Issue by havenvo** [grandnode/grandnode#563]
I tried to deploy GrandNode docker image to Heroku but the container cannot start.

1. Build GrandNode by "docker build ... "
2. Push the Docker built image to Heroku Registry and release the app
3. See error

I followed [this one](https://github.com/heroku/cli/issues/1081) to change the Dockerfile:
ENTRYPOINT ["dotnet", "Grand.Web.dll"] 
to 
CMD dotnet Grand.Web.dll
then it works fine so I wonder why don't we use CMD instead of ENTRYPOINT?

**Comment by PatrykPorabik** [comment]
It may work. I've implemented this change for now, but Heroku will have lower priority because it doesn't support .NET Core 3.0
