### ISSUE TITLE
Top Nav Links Needs Some Margin

### ISSUE THREAD

**Issue by aligoren** [grandnode/grandnode#571]
**Describe the bug**
Hi actually this isn't a bug but the nav links look stuck with badges.

**To Reproduce**
1. Go to 'Home'
2. Click on 'See nav links on the top'

**Expected behavior**
It needs some margin for example `ml-2` could be good.

**Screenshots**

![image](https://user-images.githubusercontent.com/4205423/58453451-dd691280-8123-11e9-9559-85610dd0942f.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - OS: Windows 10

**Additional context**

If you set `ml-2` class to the `span.wish-name` class. It will fix.

I saw this problem on the demo [website](http://www.demo.grandnode.com/)

**Comment by PatrykPorabik** [comment]
Hi,
Actually, it is by design. Our designers made it specially.
