### ISSUE TITLE
Currency rates doesn't take base rate into account

### ISSUE THREAD

**Issue by EvilVir** [grandnode/grandnode#572]
I have Grandnode 4.50 installed and I'm synchronizing currencies with NBP provider (kudos to @benys for that one! :). My store has base currency set to PLN (with exchange rate 1.0) and then I have bunch of other currencies for customers to choose (EUR, GBP, USD).

So I expect to put prices of products in PLN and then if client chooses to pay in different currency he will pay amount that's equivalent of PLN in choosen currency. For example:

I have product that is worth 100 PLN and current exchange rate is that 3.8 PLN equals 1 USD.

Current system behavior is so when I switch to PLN I see 100 PLN price tag but when I switch to USD I see $380 price tag which is not right. It should be $26.31 (so when customer pays me $26.31 I take that to exchange and they for each USD give me 3.8 PLNs so $26.31 * 3.8 PLN ~ 99.99 PLN and that's what the product is worth).

Solution for this is to change the `CurrencyController.ApplyRate` method so it will grab the base/primary exchange currency, get it's rate and then divide that rate by the actual rate of the values grabbed from the NBP. So in example above the exchange rate will be 1 PLN : 0.2631 USD.

I'm messing around the code anyways so I can fix that in a moment, just posting the issue here because maybe I don't understand something or how the system is working?

**Comment by benys** [comment]
According to me, you're right. My original pullrequest had exchange rate set as 1 / ratio. Because the grand multiplies ratio (not divide). Unfortunately, someone "wanted well" and deleted "1 /". Your patch looks even better!

**Comment by PatrykPorabik** [comment]
Hi Guys,

That's right. Little misunderstanding happened. You're totally correct, there appeared an error, thanks for notification. We will implement it shortly.

**Comment by EvilVir** [comment]
Cool, I already fixed this yesterday so you might as well use that PR :)

**Comment by PatrykPorabik** [comment]
By the way. I made some tests. The exchange rate is ok, our developers removed the "1 /" fully consciously. Because the problem is related with the price calculation, not with the exchange rate plugin. If we have PLN as the primary currency, we won't have 0.258 rate for dollar. It should be still, i.e 3.84. But you're right, that product should be calculated with the divided rate.

**Comment by EvilVir** [comment]
I see, ok then I will close that pull request. For me it was easier to fix the problem at the source, than track all possible situations where price is recalculated.

BTW: this isn't "1/X" but "Y/X" where "Y" is rate of base/prime currency (by default 1). If you guys do this that way, then by simple changing the base rate user will be able to adjust prices in whole system with that one value (let's say I want to rise all prices of all products by 50%, then I will just need to change the base rate to 1.5).

**Comment by KrzysztofPajak** [comment]
Hello guys,
Kamil had absolutely right with create plugin Exchange provider (NBP). His original pullrequest was correct.
Sorry for the confusion. 
Regards
Krzysztof
