### ISSUE TITLE
Avatar image does not change in 'my account' > 'avatar'

### ISSUE THREAD

**Issue by andy840119** [grandnode/grandnode#573]
**Describe the bug**
After change avatar picture in `my account' > 'avatar`, user need to clear cache to see the change.

**To Reproduce**
1. Go to 'my account' > 'avatar'
2. Upload an image
3. Upload an image again
4. `Image does not change`

**Expected behavior**
Need to change the image.

**Screenshots**
![image](https://user-images.githubusercontent.com/9100368/58542257-d16a7700-822f-11e9-8dca-3794c6a5daf4.png)

**Comment by PatrykPorabik** [comment]
Hi,

I checked it on our demo. Avatar has been changed, but your browser cached the previous one. Just click the CTRL + F5 button.

**Comment by andy840119** [comment]
Yes i know, but image should not be if server changed the image.
