### ISSUE TITLE
Kendo UI Gantt

### ISSUE THREAD

**Issue by EvilVir** [grandnode/grandnode#575]
I need to implement Gantt chart for reservations overview in admin's dashboard. I want to keep it consistent so I would use Kendo UI's Gantt. Problem is that files of that component are missing from the repository.

Would you guys be able to push these missing files so I can pull and work on that feature? Thanks!

**Comment by KrzysztofPajak** [comment]
Kendo UI Core does not contains Kendo UI Gantt in the standard. 
Please check: https://github.com/telerik/kendo-ui-core

**Comment by EvilVir** [comment]
Damn, so I need to use something else :( Anyway, thanks for info!

**Comment by KrzysztofPajak** [comment]
But you can try implement Calendar

**Comment by EvilVir** [comment]
I was thinking about using Calendar but it will be harder to read than Gantt chart. I've made already plenty of refinements of the reservations process including well-defined resources (eg. rooms in hotel), changes to order page (new range calendar, ability to order more than one resource at a time and many more).

Now I need some nice way for hotel's staff to see exactly which rooms are occupied and stuff. I think Gantt chart is perfect for this, the problem is that there aren't many good components out there.

I'll figure something out :)

**Comment by KrzysztofPajak** [comment]
Please check this component https://github.com/fullcalendar/fullcalendar

**Comment by EvilVir** [comment]
Nice one! I will use it, thank you so much @KrzysztofPajak :)
