### ISSUE TITLE
Improve reviews system - Review confirmed by purchase

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#578]
Improve reviews system - Review confirmed by purchase

**Comment by wwrighter** [comment]
Would this be a setting available to admins that they can turn on or off and customize the number of days after the status of the order is set to "delivered", grandnode would automatically send out an email requesting product review?

**Comment by PatrykPorabik** [comment]
We thought about a feature, that will mark specified review as "Confirmed by purchase" with a badge or just simple text. As a basic skeleton to the whole feature, which can be extended by a plugin. We have to talk about it.

**Comment by Krztk** [comment]
Should the review written before a purchase change status to `confirmed by purchase` after the purchase?

**Comment by scharada** [comment]
Hi Patrik.

why don't you merge all reviews in one collection. it woul be easier to manage and to report on and enhance. here is an idea. it will allow us to know who reviewed what and when ... we could enhance it to have calculated fields on every record inserted such as MinRating, AvgRating and MaxRating ... we would nly read the last record for that entity to have a rating summary ...

we could call the entity 
public class SocialRecord : BaseEntty
{
    string UserID : use who made the review.
    datetime date : date and time the review was made 
    EntityType EntityType : Enum used to determines what is being reviewed 
    String    EntityId : the id of the entity being reviewed 
    ...
    ...  the rest of the review fields

}
public enum entitytype 
{
  Vendor,
Product,
Store,
Campaign
Order,
Customer,

}
