### ISSUE TITLE
Read mail from outlook in .net core 2.1 using c#

### ISSUE THREAD

**Issue by Mahendrak12** [grandnode/grandnode#586]
Dear All,
How can i read E_Mail from outlook in .net core console application.
I am using following things-
visual studio 2017,
.net core 2.1,
Protocol: IMAP ,
Server name: outlook.office365.com
Port: 993 
please help me to find the solution.

Thank you.

Regards,
Mahendra

**Comment by KrzysztofPajak** [comment]
Hi,
Your issue is not related with application.
Regards
Krzysztof
