### ISSUE TITLE
Add filter by store on bulk edit product page

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#588]
Add filter by store on bulk edit product page

**Comment by dborovsky** [comment]
Hi @PatrykPorabik 

I would like contribute for grandnode. Is this task still relevant? Or maybe tell me which tasks are more priority? Thanks

**Comment by PatrykPorabik** [comment]
Hi @dborovsky ,

I think you can focus on few more important things, for example please check following issues: #468, #413, #385, #317

**Comment by dborovsky** [comment]
I  have already started this no big task and plan to finish today and send PR. 
If I have some questions about task, should I ask here or maybe you have chat for this? 

For example to return Stores list for filter must I return list where user is staff user for this store. If yes, than user can be staff more than in one store. Correct?
