### ISSUE TITLE
Error at Checkout while using login and checkout option

### ISSUE THREAD

**Issue by vijaytune** [grandnode/grandnode#591]
**Describe the bug**
Getting page not found error, when logged in from 'Login and Checkout' option.

**To Reproduce**
1. Open home page (don't login)
2. Add some products in cart
3. GoTo Cart
4. Click 'Login and Checkout' button
5. Login with valid credentials
6. Click 'Login'

**Expected behavior**
It should navigate to checkout page.

**Screenshots**
![image](https://user-images.githubusercontent.com/45359973/60801928-7bc1ac80-a195-11e9-8cf4-b5715fd85a18.png)
![image](https://user-images.githubusercontent.com/45359973/60801965-88de9b80-a195-11e9-8966-fa0cc2bb9622.png)

**Desktop (please complete the following information):**
 - Chrome

**Comment by KrzysztofPajak** [comment]
Thanks!, Fixed, please check.

**Comment by vijaytune** [comment]
Issue has been fixed. Thanks.
