### ISSUE TITLE
Checkout form is disabling when only one payment method configured

### ISSUE THREAD

**Issue by vijaytune** [grandnode/grandnode#593]
**Describe the bug**
Checkout form is disabling when only one payment method configured. 

**To Reproduce**
1. Go to '/Admin/Payment/Methods'
2. Enable only one payment method
3. Login to customer portal
4. Checkout a order
5. It will skip to 2. Payment information
6. Click 'back' button
7. See all controls not accessible

**Screenshots**
![image](https://user-images.githubusercontent.com/45359973/60814856-0a452680-a1b4-11e9-86c4-e23ac7a20ea3.png)

![image](https://user-images.githubusercontent.com/45359973/60814874-1335f800-a1b4-11e9-8933-1ebcc1b626a6.png)

![image](https://user-images.githubusercontent.com/45359973/60814883-1a5d0600-a1b4-11e9-9b3f-3c331781051a.png)

**Desktop (please complete the following information):**
 - Chrome

**Comment by vorgano** [comment]
Hi all 👋! 
Is this still an issue? I was looking at the code and I would like to know how can I help. It feels like the skipped payment does not render the html. Should it be rendered (displaying a single possible payment method) and enabled? That will not change the behaviour of skipping the section. 
Thank you.

**Comment by PatrykPorabik** [comment]
Hi @vorgano! 
Yes, it's still an issue. But the solution is to hide the Back button on the Payment information step, because in that case it's unnecessary.
