### ISSUE TITLE
Improve Build Infrastructure

### ISSUE THREAD

**Issue by Nirmal4G** [grandnode/grandnode#594]
Closed in favor of issue 600 that tracks the individual tasks.

**Comment by PatrykPorabik** [comment]
Hi! If you want, take your time! We really appreciate it! In the case of .NET Core 3, it's still preview version, so maybe it's not a good time to support it.

**Comment by Nirmal4G** [comment]
> In the case of .NET Core 3, it's still preview version, so maybe it's not a good time to support it.

Only the project file updates and no core code changes.

**Comment by Nirmal4G** [comment]
Are files `Deploying.Readme.txt` and `.deployment` needed?

**Comment by Nirmal4G** [comment]
I'm closing this for now, created a new issue to track the tasks of improving build, experience.

The first commit will always have 50% of the repo files touched, since the removal of BOM is done by a format tool. Please do update issue 600, when you guys are ready. I'll update and push those changes from latest changes you have available.

If you can merge most PRs before then, we can do it in one go. No need to run the format tool, again and again!
