### ISSUE TITLE
Improve Build Infrastructure

### ISSUE THREAD

**Issue by Nirmal4G** [grandnode/grandnode#600]
#### Repo

- Remove BOM from all files and Convert all files to UTF-8
- Update Project info (i.e. markdown) files
- Remove redundant files **(needs discussion)**
- Move Root projects to App sub-folder **(needs discussion)**

#### Editor

- Add Core EditorConfig options
- Update C# EditorConfig options **(needs discussion)**
- Update Code to match the styles **(needs discussion)**

#### Build

- Add common publish profiles
- Change global output and publish paths
- Update CI and Docker files **(needs discussion)**
- Make (ASP) .NET Core 3 Ready **(needs discussion)**

**Note**.: Will add more tasks related to Build, when I get more feedback.

**Comment by Nirmal4G** [comment]
These changes are cosmetic and in no way will influence the build output.

There are existing PRs and more changes are pending, so whenever the repo is ready (meaning most changes are done and PRs merged), I'll take the latest changes from `HEAD` and apply all the above mentioned changes.

So, When the next dev cycle begins, we'll have a consistent and predictable dev experience.

**Comment by Nirmal4G** [comment]
Please let me know here, when you guys are ready.

**Comment by Nirmal4G** [comment]
Since, you guys released v4.5. Can I open a PR for the above mentioned changes?

I will create a PR for each change. Is that OK?

**Comment by Nirmal4G** [comment]
These changes are purely cosmetic and in no way will influence the build output.

Since, you guys released v4.5. Is the Repo ready for the above changes?

**Note**: These changes might break the existing PRs.

**Comment by PatrykPorabik** [comment]
By the way, can you provide me a reason why you want to make that changes? It will improve the performance or maybe there are some another pros?

**Comment by Nirmal4G** [comment]
1. It'll definitely improve build performance. Less chars in the file means faster parsing.

2. Diffs look way more consistant. ie. No more whitespace errors occur when you create/apply patch/merge.

3. Having common output paths means less copying of assemblies.

4. Moving the App projects into a folder means we can customise each folder with `Directory.Build.props/targets`

5. Having publish profiles, means we can support a lot of methods like `WebDeploy`, `Azure`, `Azure VM`!

And finally It makes opensource contribution way easier for us and less painful for you guys in accepting them.

**Comment by Nirmal4G** [comment]
If you're interested, please let me know, as this requires a lot of cosmetic changes.
