### ISSUE TITLE
Update to ASP.NET Core 3.0

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#603]
Update to ASP.NET Core 3.0

**Comment by wwrighter** [comment]
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-9/

**Comment by PatrykPorabik** [comment]
@dborovsky would you like to get something harder to manage? We have one task related with ASP.NET Core 3.0 migration. If you want to get something easier, I will find existing task for you.

**Comment by dborovsky** [comment]
no i would try something harder

**Comment by KrzysztofPajak** [comment]
@dborovsky 
Here you find simple documentation to moved from asp.net core 2.2 to 3.0: 
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#routing-startup-code
Some of work was done. But it would be greate if we implement new features with routing. So we need to remove old version UseMvc and change to UseEndpoints.

**Comment by dborovsky** [comment]
@KrzysztofPajak thanks.  Yea, i try to implement new routing.

**Comment by PatrykPorabik** [comment]
@dborovsky Have you tried to do it?

**Comment by dborovsky** [comment]
@PatrykPorabik  yes,  but were errors and i investigated why.
