### ISSUE TITLE
Add Facebook Pixel Widget to the project

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#605]
Add Facebook Pixel Widget to the project

**Comment by dborovsky** [comment]
@PatrykPorabik  I can do it. Explain me, how customer will moderate this widget in admin panel?

**Comment by PatrykPorabik** [comment]
@dborovsky We haven't thought about its features. It's just an idea and we have to analyze the documentation, facebook pixel features and check which one will be applicable to ecommerce.
