### ISSUE TITLE
Search autocomplete panel is not closing

### ISSUE THREAD

**Issue by vijaytune** [grandnode/grandnode#609]
**Describe the bug**
Search autocomplete panel is not closing/hiding even after clicked outside the panel.

**To Reproduce**
1. Go to 'Index' page
2. Click on 'Search box'
3. Type some valid text to get result
4. Click outside the panel
5. The autocomplete list is not closing

**Expected behavior**
It should close after clicked outside the panel/textbox.

**Screenshots**
![image](https://user-images.githubusercontent.com/45359973/61879713-3e894880-af11-11e9-952d-c5f076e81824.png)

**Desktop (please complete the following information):**
 - Chrome

**Comment by PatrykPorabik** [comment]
We know about it, to be honest, it's by design.
