### ISSUE TITLE
Add "My reviews" section to Customer - My Account page

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#619]
Add "My reviews" section to Customer - My Account page and list all reviews created by particular customer.

**Comment by antigoniapower** [comment]
Hello Patryk!
Could you please give me some details about how this section should look like?
Should it be like Product reviews (approximately like this)
![image](https://user-images.githubusercontent.com/12136620/64113087-9ecd9e80-cd89-11e9-906d-6bd3aa4f134f.png)
Or should it be like in admin/customer/reviews page:
![image](https://user-images.githubusercontent.com/12136620/64113170-db00ff00-cd89-11e9-8dff-d5b8e8e399a3.png)

Will a customer be able to delete his review?

Thank you.

**Comment by PatrykPorabik** [comment]
Hello Olga,

It should be something similar to the first view. It's just a list of reviews added by particular customer. It should be a list with possibility to enter the public page of product.
