### ISSUE TITLE
Add possibility to add notes on shipments

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#620]
Add possibility to add notes on shipments

**Comment by Mac2m** [comment]
I can take that one.

**Comment by PatrykPorabik** [comment]
Sure, fantastic, if you have questions, feel free to ask :)

**Comment by Mac2m** [comment]
Got one question - does notes can be seen only for admins or it should be listed with shipments list for customers?

**Comment by PatrykPorabik** [comment]
If I were you, I would create it in the same way as order notes. So, with the checkbox "Display to customer".

**Comment by Mac2m** [comment]
Where it should be displayed to customer ? On order details page ?

**Comment by PatrykPorabik** [comment]
Yes, I think it would be the best place.

**Comment by Mac2m** [comment]
I can't load newly added string resources. Any advise how to do it ?

**Comment by PatrykPorabik** [comment]
Do you mean, that you've added new resource strings to xml files and you don't see them in your current installation? If yes, it's ok, resources are loaded during first installation. If you want to  add them to your store, just import the xml with missing resources or add them manually. If you add them to default xml file and upgrade xml file. they will be installed during installation or upgrade, so that's ok.

**Comment by Mac2m** [comment]
Yes, that's exactly what I meant :) thank you.

**Comment by sabboooo** [comment]
> 
> 
> I can't load newly added string resources. Any advise how to do it ?

If someone else searches it: Configuration -> Languages -> Choose a Language -> String Resources -> Add new record
