### ISSUE TITLE
Add Commission management

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#623]
Add Commission management

**Comment by dborovsky** [comment]
@PatrykPorabik Do you have more information how We need realize it? I can help

**Comment by KrzysztofPajak** [comment]
1. Allow to store owner to set commission percentage rate for each vendor (admin panel)
2. Every product sold by the vendor has their commission rate applied (saved in orderItem collection, during the placing order - new field)
3. The amount taken as commission can be view in the order details in admin panel (order positions)

**Comment by dborovsky** [comment]
@KrzysztofPajak I will do this feature.  have already started.

**Comment by dborovsky** [comment]
@KrzysztofPajak @PatrykPorabik  

> Every product sold by the vendor has their commission rate applied (saved in orderItem collection, during the placing order - new field)

For example product costs 15 usd, vendor commission is 10%. Total price will be 15 usd + 10%?
Or price for customer will be staying 15 usd?

**Comment by KrzysztofPajak** [comment]
@dborovsky  
Price for customer will be still 15 usd, we need only add new field, commission for vendor and will be calculated by round(price*vendor_commision)/100),2)

**Comment by dborovsky** [comment]
Should the field be added here? 

![Screenshot_1](https://user-images.githubusercontent.com/3728303/65129624-5d352880-da04-11e9-9430-c0f419e26f5a.png)

**Comment by KrzysztofPajak** [comment]
Definitely no, Commission should be visible only in admin panel (in the order details)
![image](https://user-images.githubusercontent.com/16772986/65130287-6a9ae480-d9fd-11e9-93f5-4aba3fac6057.png)
