### ISSUE TITLE
Admin--Dashboard--DateFilters are not working

### ISSUE THREAD

**Issue by vijaytune** [grandnode/grandnode#632]
**Describe the bug**
Admin--Dashboard--DateFilters are not working.

**To Reproduce**
1. Login into Admin panel
2. Click on Dashboard from left menu
3. Click Dashboard
4. Change the Date-Filters
5. No filters happening.

**Expected behavior**
It should bring the data as per date selection.

**Screenshots**
![image](https://user-images.githubusercontent.com/45359973/64153032-8625bd00-ce4b-11e9-90e6-9cf9bd1b3c8c.png)

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by PatrykPorabik** [comment]
We will fix it. Thanks for notification.

**Comment by odin88** [comment]
I can't seem to replicate the issue.
When you change the date, can you check the ajax call ?
Does the date change when u change the date ?

![image](https://user-images.githubusercontent.com/680300/64722052-41132200-d500-11e9-9c9d-c6ad9b7eb3cc.png)
