### ISSUE TITLE
Admin-->Dashboard-->Statistics-->DateFilter is not as expected

### ISSUE THREAD

**Issue by vijaytune** [grandnode/grandnode#633]
**Describe the bug**
Admin-->Dashboard-->Statistics-->DateFilter is not as expected.

**To Reproduce**
1. Login into Admin panel
2. Click on Dashboard from left menu
3. Click Statistics
4. See the DateFilter

**Expected behavior**
It should show the calendar dropdown and user able to choose the date range apply for filtered data.

**Screenshots**
![image](https://user-images.githubusercontent.com/45359973/64153092-b3726b00-ce4b-11e9-9c4c-c732603bafbe.png)

**Desktop (please complete the following information):**
 - Browser - chrome

**Comment by PatrykPorabik** [comment]
Hi,
It's by design. It's just current date. Dropdown has never been here, because on this page you can see stats for many periods of time, not only for selected date range. That's why you have field "This week", "This Month", "This year".
