### ISSUE TITLE
Exporting customers is having issue with Country

### ISSUE THREAD

**Issue by vijaytune** [grandnode/grandnode#634]
**Describe the bug**
Exporting customers is having issue with Country.

**To Reproduce**
1. Go to 'Admin-->Configuration-->Settings-->Customer Settings'
2. Click on 'Customer Form Fields'
3. Check Country enabled and required
4. Go to 'Admin-->Customers-->AddNew'
5. Add customer with a Country and Save the changes
6. Go to 'Admin-->Customers'
7. Click export and choose any export option
8. See the error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45359973/64182497-ef2a2680-ce85-11e9-8d63-bec942d40930.png)

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by dborovsky** [comment]
I will check today this issue. And which issues are more important today?

**Comment by vijaytune** [comment]
I don't have any priority. I just submitted after I notice the issue.

**Comment by PatrykPorabik** [comment]
Fixed. Thanks @dborovsky
