### ISSUE TITLE
Enable SSL option is not considered

### ISSUE THREAD

**Issue by vijaytune** [grandnode/grandnode#640]
**Describe the bug**
The SSL option available at Store configuration is not considered.

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'Stores'
3. Select your store for edit
4. Check 'SSL enabled'
5. Enable one page checkout
6. Visit the cart page (need build already)
7. Click checkout
8. See the redirect to cart page

**Expected behavior**
The following methods are called with the UseSSL parameter by hard-coded value 'false'.
GetThisPageUrl()
GetStoreLocation()
Hence the http URL used and CORS exception.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by vijaytune** [comment]
In addition, the following code is not sending 'true' for some of the environment(IIS-SSLenabled sites).
_httpContextAccessor.HttpContext.Request.IsHttps

```
        public virtual bool IsCurrentConnectionSecured()
        {
            if (!IsRequestAvailable())
                return false;

            //check whether hosting uses a load balancer
            //use HTTP_CLUSTER_HTTPS?
            if (_hostingConfig.UseHttpClusterHttps)
                return _httpContextAccessor.HttpContext.Request.Headers["HTTP_CLUSTER_HTTPS"].ToString().Equals("on", StringComparison.OrdinalIgnoreCase);

            //use HTTP_X_FORWARDED_PROTO?
            if (_hostingConfig.UseHttpXForwardedProto)
                return _httpContextAccessor.HttpContext.Request.Headers["X-Forwarded-Proto"].ToString().Equals("https", StringComparison.OrdinalIgnoreCase);

            return _httpContextAccessor.HttpContext.Request.IsHttps;
        }
```

**Comment by PatrykPorabik** [comment]
Hello Vijay,

In the System -> System Information you will find the status of your SSL configuration. If you made something wrong, you will see something different than:
![image](https://user-images.githubusercontent.com/16773025/64883523-e2fd5080-d65f-11e9-8f43-561d35c20882.png)

Have you configured the proper settings in the appsettings.json file? We've tested it on few environments and we've never had similar issues with correct server configuration.

**Comment by vijaytune** [comment]
Thanks.
The system information shows http scheme request as false.
This caused at AWS-EC2 instance-Loadbalance environment.

![image](https://user-images.githubusercontent.com/45359973/64904915-9dd42f80-d6ee-11e9-9c06-6336242057e3.png)

![image](https://user-images.githubusercontent.com/45359973/64904972-2eab0b00-d6ef-11e9-86dc-c3ab91cf5073.png)

I am using AWS EC2 - Windows 2016 - IIS 10.0 - UrlRewrite

I have set the following in appsettings.json
```
{
  "Hosting": {
    //Set to "true" the settings below if your hosting uses a load balancer. It'll be used to determine whether the current request is HTTPS
    "UseHttpClusterHttps": true,
    "UseHttpXForwardedProto": true,
```
Web.Config

```
<rewrite>
      <rules>
        <rule name="Redirect to HTTPS" enabled="true" stopProcessing="true">
          <match url="^(.*)$" />
          <conditions>
            <add input="{HTTP_X_FORWARDED_PROTO}" pattern="https" negate="true"/>
          </conditions>
          <action type="Redirect" url="https://{HTTP_HOST}{REQUEST_URI}" appendQueryString="false" redirectType="Permanent"/>
        </rule>
      </rules>
    </rewrite>
```

**Comment by KrzysztofPajak** [comment]
Hi,
It's hard to say where could be the problem.
We made test SSL with load balancer on DigitalOcean and we implemented successfully. 
We can send your request to our support specialist but please contact by https://grandnode.com/contactus 
Regards
Krzysztof

**Comment by vijaytune** [comment]
I don't have any need to get fixed this issue. I caught during my experiment and just notified you.
Hence closing this issue.
Thanks.

**Comment by gamethe7** [comment]
Hello @vijaytune could you please help me i am also facing the same issue.
![image](https://user-images.githubusercontent.com/16897354/103304712-757e5a80-4a31-11eb-864d-f8c02f0bc8fe.png)
[](url)

**Comment by PatrykPorabik** [comment]
@gamethe7 What's wrong with your config? Both settings are fine. Just enable SSL in Admin panel -> Configuration -> Stores -> Edit your store details. Mark the proper checkbox, provide secure url, and that's all.

**Comment by gamethe7** [comment]
@PatrykPorabik I have enabled the SSL from admin as well. The main issue i am facing is 
When I Click checkout and one page checkout is enabled. After clicking the continue button on Billing Address the page is redirecting to the cart page. Test the same scenario using the live database on local machine and it is working fine.
I have attached the appsetting as well. Could you please help me to resolve the [issue.]


![image](https://user-images.githubusercontent.com/16897354/103334408-4ac7ec80-4a99-11eb-8d91-c5420e6c6852.png)

**Comment by PatrykPorabik** [comment]
Please post this question with a screenshot on our [community forum.](https://grandnode.com/boards) It's not a developer issue, I will answer you directly on the forum.
