### ISSUE TITLE
Staff discounts/promotions management

### ISSUE THREAD

**Issue by gelinski** [grandnode/grandnode#652]
Allow staff to manage discounts. In Discounts list, staff only can see discounts for their store. When creating new discount, sets automatically the store based in associated staff store. This functionality cannot be restricted to Administrator, once the staff also is a store manager and can create promotions only for its store, but cannot view other stores promotions (competition issue).

**Comment by PatrykPorabik** [comment]
Hi,
Thanks for suggestion. It will be added in one of the next version of GrandNode.
