### ISSUE TITLE
Add API Versioning + SwaggerUI. SwaggerDoc to APIs

### ISSUE THREAD

**Issue by scharada** [grandnode/grandnode#655]
it would be good to have API versioning with swagger UI and Doc

**Comment by PatrykPorabik** [comment]
Unfortunately, OData has problems with Swagger. So we don't have plans to add it.

**Comment by scharada** [comment]
Hi @PatrykPorabik . thanks for the reply.
i have been following the new OData package and it's still not compatible with net core 3.
but i had a need to add versioning so i created a web api project using swagger using the same structure as the Grand.Api project. however i encoutered the following problem and was hoping you could point me to the right place to look at resolving it.


the problem i am having is the following :
here is my ApiAuthenticationRegistrar.cs 

`    public partial class ApiAuthenticationRegistrar : IExternalAuthenticationRegistrar
    {
        public void Configure(AuthenticationBuilder builder)
        {
            //builder.Services.AddAuthentication (x =>
            //{
            //    x.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
            //    x.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            //})
            builder.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
            {
                var apiConfig = EngineContext.Current.Resolve<ApiConfig>();
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = apiConfig.ValidateIssuer,
                    ....
                    .... 
`
if i comment out the commented lines which do not exist in the Grand.Api version, everything works on the web app side as usual but the web api has the following issue :
- all secure methods in controller which should return unauthorized return 200 but empty result.

if i uncomment them, the web api behaves correctly but receive many errors on the web app side as the authentication scheme changes or os somehow overridden...

any idea why this happens or what needs to done to solve this ?

thank you in advance.

**Comment by kibria06cse** [comment]
@PatrykPorabik Is there any alternative solutions for swagger?

**Comment by PatrykPorabik** [comment]
To be honest, please look at this commit - d49ee84
We've extended API to use the Swagger UI.
