### ISSUE TITLE
Two Factor Authentication for users

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#661]
@dborovsky , we are thinking about adding possibility to set two factor authentication for users. 

In the ideal scenario, it should work in the following way:
Admin specify if two factor authentication is possible or not. As a simple setting in Configuration -> Settings. Then on the login page, after filling the standard form, will get the textbox where they will be forced to enter the code coming from the app. We would like to use the Microsoft Authenticator app to handle the code generation.

**Comment by dborovsky** [comment]
i will do it

**Comment by dborovsky** [comment]
I am now implementing following logic:
Admin specify if two factor authentication is possible or not. As a simple setting in Configuration -> Settings.

If two factor auth is enable, than user will have possibility to set 2factorauth in his profile with following scenario:

[https://medium.com/free-code-camp/how-to-set-up-two-factor-authentication-on-asp-net-core-using-google-authenticator-4b15d0698ec9](Setting for user 2factorauth)


Is this logic correct?

**Comment by Orlys** [comment]
How about [GoogleAuthenticator](https://www.nuget.org/packages/GoogleAuthenticator)?

**Comment by PatrykPorabik** [comment]
I didn't dive into the topic, but I guess it doesn't matter which app will be used. It's just about the code authentication, but if @dborovsky analyzed that, maybe will be able to say something more about that.

**Comment by dborovsky** [comment]
if we speake about auth app, it's no matter.

**Comment by dborovsky** [comment]
I finished about 80%. Sorry for delay. I was on holliday. I will try to do commits as soon as possible.

**Comment by scharada** [comment]
maybe this can help
https://bitbucket.org/devinmartin/otp-sharp/src/default/
https://github.com/kspearrin/Otp.NET

**Comment by scharada** [comment]
@dborovsky , will 2FA be used in login and registration flow ?

**Comment by dborovsky** [comment]
@scharada only  login and registration flow

**Comment by dborovsky** [comment]
@PatrykPorabik  I created PR. 

Maybe code not very well. I will a bit refactor.
I think we must add posibility for every user enable or disable 2fa. This feature must be implemented in admin panel of every user. 

-  User will click enable 2fa
-than opening window with qrcode,
- user uses one time authentication application
- and when user will sign in, don`t need to show again qrcode, only input digital code from auth application.
