### ISSUE TITLE
Error loading on static files (CSS/JS) After publishing on my linux machine with ngnix server 

### ISSUE THREAD

**Issue by Navaneeth-Ewall** [grandnode/grandnode#664]
After publishing grandnode on my linux machine with ngnix server. 
1) .net core 3.0,
2) mongo db 4.2

When i'm running a url 127.0,0,1 (localhost), it's working fine , but i have set reverse proxy with local ip  address , i'm getting error like css and js are not loading  , they running on https . But i didn't install any ssl on machine . kindly refer the below screenshot , pls help me to solve this issues . 

![screeshot](https://user-images.githubusercontent.com/52706508/68014911-d5a33080-fcb6-11e9-8de1-db5eb25d7f85.png)

Thanks in advance

**Comment by PatrykPorabik** [comment]
It's something related with your server configuration. Can you share with us details about the reverse proxy configuration?

**Comment by Navaneeth-Ewall** [comment]
Hi PatrykPorabik !
Thanks for your reply 
here my reverse proxy configuration code on ngnix server ,


# Default server configuration
#
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	# SSL configuration
	#
	# listen 443 ssl default_server;
	# listen [::]:443 ssl default_server;
	#
	# Note: You should disable gzip for SSL traffic.
	# See: https://bugs.debian.org/773332
	#
	# Read up on ssl_ciphers to ensure a secure configuration.
	# See: https://bugs.debian.org/765782
	#
	# Self signed certs generated by the ssl-cert package
	# Don't use them in a production server!
	#
	# include snippets/snakeoil.conf;

	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;
	
	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		#try_files $uri $uri/ =404;
	proxy_pass	http://127.0.0.1:5000;
	proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
	}

	# pass PHP scripts to FastCGI server
	#
	#location ~ \.php$ {
	#	include snippets/fastcgi-php.conf;
	#
	#	# With php-fpm (or other unix sockets):
	#	fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
	#	# With php-cgi (or other tcp sockets):
	#	fastcgi_pass 127.0.0.1:9000;
	#}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	#location ~ /\.ht {
	#	deny all;
	#}
}

**Comment by KrzysztofPajak** [comment]
@Navaneeth-Ewall Go to appsettings.json (in AppData folder), find setting UseDefaultSecurityHeaders and set on false

**Comment by Navaneeth-Ewall** [comment]
Hi , KrzysztofPajak , it's working 
Thank you so much.
