### ISSUE TITLE
Getting Error while enable Api in app_settings.json file. 

### ISSUE THREAD

**Issue by Navaneeth-Ewall** [grandnode/grandnode#665]
I'm running grandnode on visual studio 2019 with dot-net core 3.0  , when i enable Api in app_settings.json file ,getting error like 

**TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.Internal.ActionConstraintCache' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.**

![api_error](https://user-images.githubusercontent.com/52706508/68270875-e40d9580-0084-11ea-8b18-3d7f58de997e.png)

kindly help me to solve this issue . 
Thanks in Advance.

**Comment by TTomu** [comment]
API using oData, which does not support Core 3.0 (yet). We recommend to use stable version of GrandNode - 4.50

**Comment by Navaneeth-Ewall** [comment]
Hi **TTomu** 
Thank you so much , now it's working,

But when i create api token creation i'm getting response  like **404 Not Found** .
Following code will be my app setting file.

 **"Api": {
    "Enabled": true,
    "SecretKey": "reset!23",
    "ValidateIssuer": false,
    "ValidIssuer": "",
    "ValidateAudience": false,
    "ValidAudience": "",
    "ValidateLifetime": true,
    "ValidateIssuerSigningKey": true,
    "ExpiryInMinutes": 1440,
    //generate system model
    "SystemModel":  true
  }**

I followed  this document http://docs.grandnode.com/web-api

step 1 : i have created the api user
step 2: open postman , set a post method  
         **Authorization tab:  Type : No Auth
         Headers : Content-Type : application/json
         Body :  select raw  ,Enter api user email and encoded password
{
	"email":"admin@yourstore.com",
    "password":"Z3JhbmRub2Rl"
}** 
    How to solve this issue
thanks in advance.
