### ISSUE TITLE
Plugins - Differently building at latest version of visual studio 2019

### ISSUE THREAD

**Issue by vijaytune** [grandnode/grandnode#668]
**Plugins - Differently building at latest version of visual studio 2019**
I am using Visual Studio 2019 to build and publish the grandnode application. The build/publish produces the files at plugins (Google, Facebook and BrainTree) differently previous version of VS2019 and latest version of VS2019.

I am using Microsoft Visual Studio Community 2019 - Version 16.3.7

**Screenshots**
![image](https://user-images.githubusercontent.com/45359973/68366424-4df76f00-0159-11ea-869f-4d2d63fb82df.png)

![image](https://user-images.githubusercontent.com/45359973/68366432-5485e680-0159-11ea-971d-1da696ddde65.png)

**Comment by TTomu** [comment]
Thank you, already notice difference related to VS2019. We will investigate it.

**Comment by KrzysztofPajak** [comment]
@vijaytune Which version of grandnode do you use?

**Comment by vijaytune** [comment]
Version 4.50

**Comment by KrzysztofPajak** [comment]
This problem was resolved in development version 4.60

**Comment by vijaytune** [comment]
I am unable relocate the fix myself. Could you please let me know the fix#?

**Comment by PatrykPorabik** [comment]
The easiest way is to merge the changes from current version. But please note it's development version, so it may contains bugs, the changes will be officially released when we will release the 4.60 version.
