### ISSUE TITLE
How to disable GrandNode cache ?

### ISSUE THREAD

**Issue by ghost** [grandnode/grandnode#682]
I haven't found how to do it

**Comment by Leonardo-Ferreira** [comment]
As far as I can tell you can't really disable caching 100%... May I ask what are you trying to accomplish?

**Comment by dctremblay** [comment]
I have some issues that really seems to be cache related.
And also I plan to develop lots of stuff on GrandNode, it is a good practice to disable caches while development.

**Comment by Leonardo-Ferreira** [comment]
a possible workaround would be using redis cache, and run a really small cache, where whatever data would be constantly pushed out (https://stackoverflow.com/questions/33115325/how-to-set-redis-max-memory/33119590)
Try a value such as 1kb... but beware, the performance will drop significantly and other issues might arise

**Comment by Leonardo-Ferreira** [comment]
This question got stuck in my head, not in the sense of turning off the cache, but shouldn't we have 2 levels of cache? lvl 1 would be in-process-memory and lvl 2 a distributed (redis)? wether we like or not, when refreshing the main page alone, (for the sample data installation)we make 88 roundtrips to redis... if some of that info, like the one used to authorise, is locally available, we could save some precious time there!
Any thoughts @PatrykPorabik @dborovsky?

**Comment by Leonardo-Ferreira** [comment]
In case you're wondering, here are the 88 keys in request order:
"HIT" for key: "Grand.stores.all"
"HIT" for key: "Grand.language.all-False"
"HIT" for key: "Grand.currency.all-False"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-home_page_top-DefaultClean"
"HIT" for key: "Grand.slider-5de56bf3e7ae9309fdc786f2-HomePage-"
"HIT" for key: "Grand.plugins.widgets.slider.pictureurl-5de56cf6e7ae9309fdc7c075"
"HIT" for key: "Grand.plugins.widgets.slider.pictureurl-5de56cf6e7ae9309fdc7c076"
"HIT" for key: "Grand.pres.topic.details.bysystemname-HomePageText-5de56bf3e7ae9309fdc78703-5de56bf3e7ae9309fdc786f2-5de56bf4e7ae9309fdc7884b"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-home_page_before_categories-DefaultClean"
"HIT" for key: "Grand.pres.category.homepage-5de56bf4e7ae9309fdc7884b-5de56bf3e7ae9309fdc786f2-5de56bf3e7ae9309fdc78703-False"
"HIT" for key: "Grand.Picture.5de56ccfe7ae9309fdc7a6a6.350"
"HIT" for key: "Grand.Picture.5de56ccfe7ae9309fdc7a6ae.350"
"HIT" for key: "Grand.Picture.5de56cd0e7ae9309fdc7a6b8.350"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-home_page_before_products-DefaultClean"
"HIT" for key: "Grand.pres.product.detailspictures-5de56cdde7ae9309fdc7a919-415-True-Grand.Core.Domain.Localization.Language-False-5de56bf3e7ae9309fdc786f2"
"HIT" for key: "Grand.discount.all-False-5de56bf3e7ae9309fdc786f2--"
"HIT" for key: "Grand.category.id-5de56cd0e7ae9309fdc7a6bb"
"HIT" for key: "Grand.currency.id-5de56bf3e7ae9309fdc78704"
"HIT" for key: "Grand.discount.all-False-5de56bf3e7ae9309fdc786f2--"
"HIT" for key: "Grand.pres.product.detailspictures-5de56cd3e7ae9309fdc7a70c-415-True-Grand.Core.Domain.Localization.Language-False-5de56bf3e7ae9309fdc786f2"
"HIT" for key: "Grand.category.id-5de56ccee7ae9309fdc7a6a1"
"HIT" for key: "Grand.currency.id-5de56bf3e7ae9309fdc78704"
"HIT" for key: "Grand.manufacturer.id-5de56cd2e7ae9309fdc7a6ce"
"HIT" for key: "Grand.pres.product.detailspictures-5de56cd2e7ae9309fdc7a6e2-415-True-Grand.Core.Domain.Localization.Language-False-5de56bf3e7ae9309fdc786f2"
"HIT" for key: "Grand.discount.all-False-5de56bf3e7ae9309fdc786f2--"
"HIT" for key: "Grand.category.id-5de56ccee7ae9309fdc7a69f"
"HIT" for key: "Grand.pres.product.detailspictures-5de56cd6e7ae9309fdc7a833-415-True-Grand.Core.Domain.Localization.Language-False-5de56bf3e7ae9309fdc786f2"
"HIT" for key: "Grand.discount.all-False-5de56bf3e7ae9309fdc786f2--"
"HIT" for key: "Grand.category.id-5de56ccfe7ae9309fdc7a6a9"
"HIT" for key: "Grand.Picture.5de56cdde7ae9309fdc7a91d.200"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-productbox_addinfo_before-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-productbox_addinfo_after-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-productbox_addinfo_middle-DefaultClean"
"HIT" for key: "Grand.Picture.5de56cd3e7ae9309fdc7a730.200"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-productbox_addinfo_before-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-productbox_addinfo_after-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-productbox_addinfo_middle-DefaultClean"
"HIT" for key: "Grand.Picture.5de56cd2e7ae9309fdc7a6fc.200"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-productbox_addinfo_before-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-productbox_addinfo_after-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-productbox_addinfo_middle-DefaultClean"
"HIT" for key: "Grand.Picture.5de56cd6e7ae9309fdc7a838.200"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-productbox_addinfo_before-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-productbox_addinfo_after-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-productbox_addinfo_middle-DefaultClean"
"HIT" for key: "Grand.pres.category.homepage-fp-5de56bf4e7ae9309fdc7884b-5de56bf3e7ae9309fdc786f2-5de56bf3e7ae9309fdc78703-False"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-home_page_before_best_sellers-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-home_page_before_manufacturers-DefaultClean"
"HIT" for key: "Grand.pres.manufacturer.navigation.homepage-5de56bf3e7ae9309fdc786f2-5de56bf3e7ae9309fdc78703"
"HIT" for key: "Grand.pres.manufacturer.navigation.homepage-fp-5de56bf4e7ae9309fdc7884b-5de56bf3e7ae9309fdc786f2"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-home_page_before_news-DefaultClean"
"HIT" for key: "Grand.pres.news.homepage-5de56bf3e7ae9309fdc78703-5de56bf3e7ae9309fdc786f2"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-home_page_before_blog-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-home_page_before_poll-DefaultClean"
"HIT" for key: "Grand.pres.poll.homepage-5de56bf3e7ae9309fdc78703-5de56bf3e7ae9309fdc786f2"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-home_page_bottom-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-main_column_before-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-main_column_after-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-body_start_html_tag_after-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-notifications-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-header-DefaultClean"
"HIT" for key: "Grand.pres.currencies.all-5de56bf3e7ae9309fdc78703-5de56bf3e7ae9309fdc786f2"
"HIT" for key: "Grand.pres.languages.all-5de56bf3e7ae9309fdc786f2"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-header_selectors-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-header_links_before-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-header_links_after-DefaultClean"
"HIT" for key: "Grand.pres.logo-5de56bf3e7ae9309fdc786f2-DefaultClean-False"
"HIT" for key: "Grand.pres.category.all.searchbox-5de56bf4e7ae9309fdc7884b-5de56bf3e7ae9309fdc786f2"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-searchbox_before_search_button-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-searchbox-DefaultClean"
"HIT" for key: "Grand.pres.category.all-5de56bf3e7ae9309fdc78703-5de56bf4e7ae9309fdc7884b-5de56bf3e7ae9309fdc786f2"
"HIT" for key: "Grand.pres.topic.topmenu-5de56bf3e7ae9309fdc78703-5de56bf3e7ae9309fdc786f2-5de56bf4e7ae9309fdc7884b"
"HIT" for key: "Grand.pres.manufacturer.navigation.menu-5de56bf3e7ae9309fdc78703-5de56bf3e7ae9309fdc786f2"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-header_menu_before-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-header_menu_after-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-content_before-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-content_after-DefaultClean"
"HIT" for key: "Grand.pres.topic.footer-5de56bf3e7ae9309fdc78703-5de56bf3e7ae9309fdc786f2-5de56bf4e7ae9309fdc7884b"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-footer-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-body_end_html_tag_before-DefaultClean"
"HIT" for key: "Grand.pres.widget-5de56bf3e7ae9309fdc786f2-head_html_tag-DefaultClean"
"HIT" for key: "Grand.stores.all"
"HIT" for key: "Grand.language.all-False"
"HIT" for key: "Grand.currency.all-False"
"HIT" for key: "Grand.customer.action.type"
"HIT" for key: "Grand.stores.all"
"HIT" for key: "Grand.language.all-False"
"HIT" for key: "Grand.currency.all-False"

**Comment by dborovsky** [comment]
> This question got stuck in my head, not in the sense of turning off the cache, but shouldn't we have 2 levels of cache? lvl 1 would be in-process-memory and lvl 2 a distributed (redis)? wether we like or not, when refreshing the main page alone, (for the sample data installation)we make 88 roundtrips to redis... if some of that info, like the one used to authorise, is locally available, we could save some precious time there!
> Any thoughts @PatrykPorabik @dborovsky?

I think separate on two level is no good solution. 

Because memory cache is usefull:
- In development and testing scenarios.
- When a single server is used in production and memory consumption isn't an issue.

**Comment by Leonardo-Ferreira** [comment]
Regarding development and testing scenarios, in my opinion, in-memory cache is NOT a good/helpful thing. 
A very common source of bugs and errors incur when the cache expires, and with in-memory cache, reproducing this scenario is quite difficult comparing to executing `flushall` on redis. Another scenario is when you need a empty cache to perform a test: without redis, the easiest way to stop and restart the app.
What about when you want to debug troubleshoot the information cache? On redis, there are several tools (from `redis-cli` to very expensive ones) to help you manipulate the cache... As far as I know, there are no tools to manipulate in-memory cache... As far as I know, there is no "List Keys", "Get/Set Values" or even "Get Cache Size" for in-memory cache, in order to get those, you'll have to dump the process and count the refs...

Now regarding production scenarios, multi level cache is a pattern observed in several large scale apps. [On this post](https://nickcraver.com/blog/2019/08/06/stack-overflow-how-we-do-app-caching/), Nick Craver, explains the why's on their approach on StackExchange. The idea behind it is simple: The more the information is required, the closer it should be to the processor. For example, keys that are utilised on request middleware (Grand.Stores.All for example) should be on a in-memory cache because they will be used on every-single-request...

**Comment by dborovsky** [comment]
i am reading your article now.  very interesting. We can try to implement this, but main team of grandnode shoul say anything about this. 

I agree with you abot disabling cache in test and develop mode.

**Comment by Leonardo-Ferreira** [comment]
@dborovsky, the article very lengthy and complete no? hehehehe

Yes, this is something that everyone should be onboard with, this will be a long undertake.

**Comment by scharada** [comment]
a remake of the cache in grand is a great idea ... i think we should start by customizing the current caching mechanism which will open a way to changing the way it works.
imho we should start by making the current caching configurable. meaning that we should have a system setting defining what entities and data should and should not be cached.
then we could add how each entity/data should be cached (inmemory, redis....)
it will also allow for a gradual migration to a new cache while evaluating performance piece by piece instead of making the change then revert back in case of problems...
it would also allow for  mixing and matching caching and customize it to each setup and environment.

**Comment by Leonardo-Ferreira** [comment]
>  we should have a system setting defining what entities and data should and should not be cached.
This is usually referred to as "Cache Aggressiveness". Basically we cache everything and to each key we assign a level of priority, and like logging, we set which level of caching we want/need. Also, when caching, each key should be able to define it's expiration (today, everything lasts for 60 minutes), and it's desired level of caching: redis_only, redis+in_memory, in_memory_only...

**Comment by Leonardo-Ferreira** [comment]
@scharada I started working on this matter on #721... I hope it to be approved soon so I can improve upon it. 
I'm planning to move the keys that are used on middleware to in_memory cache, regardless if redis is active or not. IF redis is on, I'll use it's pub/sub feature to evict the in-memory cache of all the hosts...

**Comment by dborovsky** [comment]
@Leonardo-Ferreira  @scharada  I can help you. Just tell me. I need more undestanding how it will be work in the future
