### ISSUE TITLE
It should be possible to create orders through admin

### ISSUE THREAD

**Issue by NathalieTremblay** [grandnode/grandnode#694]

**Comment by PatrykPorabik** [comment]
We want to create a plugin to handle Advanced B2B Features and it will be one of its features.

**Comment by wwrighter** [comment]
Most major platforms make it possible for admins to create "draft orders" that generate a link that can then be sent to a customer, making the process of purchase very simple as items are already selected and in some cases information related to the customers billing or shipping addresss may have already been filled out for them. 

I am not sure this feature is exclusive to B2B

**Comment by PatrykPorabik** [comment]
You can do it now with impresonate session.
