### ISSUE TITLE
QUESTION: using mongodb Polymorphism

### ISSUE THREAD

**Issue by scharada** [grandnode/grandnode#702]
@TTomu  i am trying to use polymorphism as specified by mongodb docs as follows : 
`[BsonDiscriminator(RootClass = true)]
[BsonKnownTypes(typeof(Cat), typeof(Dog)]
public class Animal 
{
}
[BsonKnownTypes(typeof(Cat), typeof(Dog))]
public class Animal 
{
}

[BsonKnownTypes(typeof(Lion), typeof(Tiger))]
public class Cat : Animal 
{
}

public class Dog : Animal 
{
}

public class Lion : Cat 
{
}

public class Tiger : Cat 
{
}`
the Repository used still creates separate classes for dogs and cats instead of Animal only .. any idea what needs to be changed to make it work ?

**Comment by Leonardo-Ferreira** [comment]
I'm sorry, but I don't see the relevance of this question here. Shouldn't you ask this @ Stackoverflow or similar?

**Comment by scharada** [comment]
@Leonardo-Ferreira  oh thank you for pointing me to stack ... really ????  if it's not relevant to you that the current repository used in grand does not apply polymorphic structures according to the mongo driver then maybe you should not be commenting this at all ...

**Comment by Leonardo-Ferreira** [comment]
@scharada I'm sorry if I offended you, I didn't mean to... Please accept my deepest condolences.
Perhaps you can rephrase your question, indicating the actual scenario you're trying to implement? Maybe also committing and sharing the code so we can reproduce locally?

**Comment by KrzysztofPajak** [comment]
@scharada If you don't want create new repository but you need use another class, please check this:
[https://github.com/grandnode/grandnode/blob/develop/Grand.Api/Services/CustomerApiService.cs](url)
In this file we use collection of type IMongoCollection<VendorDto> _vendor which commes from Domain.Vendor (_mongoDBContext.Database().GetCollection<VendorDto>(typeof(Core.Domain.Vendors.Vendor).Name);)

**Comment by scharada** [comment]
@Leonardo-Ferreira don't worry ... it's ok.
@KrzysztofPajak i've seen that before . that is not what i am trying to do. here is the scenario. 
think of the Reviews we already have in Grand (Product Review and Vendor Review). both reviews have few common properties and some others that might be specific to each review type.
in the current code, we have separate classes that represent each of the reviews , each stored in its own collection.
the solution a am looking for which could be also implemented in other scenarios is the following 
1 - have a base class called "BaseReview" that contains the common properties to all reviews
2 - then create ProductReview and VendorReview classes, both inherits from the BaseReview 
this would create just one collection , NOT 2 ... where both types of reviews a re stored and the differentiator is called Descriminator.  if you look at the sample code in my previous comment you'll see how that is done (through Attributes) although it can also be done through mongo classmaps  ...
there is a number of places where this could be used in grand and could give much more flexibility to  the platform , save db space, less code, better product handling and take advantage of the NoSql nature of mongo. 
the first place where i would start is the Product Entity where i would have a BaseProduct as an abstract class that holds the common properties of all product types, and SimpleProduct, GroupedProduct, ReservationProduct etc... which all inherit from the BaseProduct but can have different structures and all are stored in the same collection ... 

so to come back to my question : mongo C# driver already supports polymorphism ... but if i create a sample baseclass , decorate it with attributes and create 2 child classes that inherit from it, the repo still creates different collections for each of the child classes. 
this is where i asked if there is anything i can do to correct it and maintain the compatibility with the the rest ...
i hope this helps ...

**Comment by scharada** [comment]
i'll try to fix this and share it ... maybe it'll be used by others.
