### ISSUE TITLE
Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.

### ISSUE THREAD

**Issue by sergey-messer** [grandnode/grandnode#703]
Environment: GN 4.6 (Core 3.0) PayPal Standard Plugin 
Execption:
System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead. at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count) at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize) at System.IO.Stream.CopyTo(Stream destination) at Grand.Plugin.Payments.PayPalStandard.Controllers.PaymentPayPalStandardController.IPNHandler() at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.

For reproduce try PayPal IPNSimulator
https://developer.paypal.com/developer/ipnSimulator/
For Url https://YOUR_SHOP/plugins/paymentpaypalstandard/ipnhandler

Solution:
Set Kestrel option AllowSynchronousIO = true

\Grand.Web\Program.cs
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .CaptureStartupErrors(true)
                .UseSetting(WebHostDefaults.PreventHostingStartupKey, "true")
                .UseStartup<Startup>()
                **.ConfigureKestrel((context, options) =>
                {
                    options.AllowSynchronousIO = true;
                })**
                ;
 CREDIT:
https://stackoverflow.com/questions/55052319/net-core-3-preview-synchronous-operations-are-disallowed
https://stackoverflow.com/questions/47735133/asp-net-core-synchronous-operations-are-disallowed-call-writeasync-or-set-all

**Comment by PatrykPorabik** [comment]
Thanks for notification, it will be fixed in the incoming version of GrandNode.
