### ISSUE TITLE
Wrong width calculation between mobile and desktop view 

### ISSUE THREAD

**Issue by sergey-messer** [grandnode/grandnode#709]
File:
\Grand.Web\wwwroot\scripts\public.common.js
Function:
function **mainMenuReplace**() {
    if ($(window).width() < 991) {
***
==========================================
Must be
if (window.innerWidth  <= 991)
==========================================

To reproduce try to resize width of window about +- 991 px and you will see both menues mobile and Desktop + Logo hidden.

**Comment by PatrykPorabik** [comment]
Hi Sergey,

We are reworking the default clean theme a little. We will check the mentioned issue, thanks for notification.

**Comment by PatrykPorabik** [comment]
It has been fixed. Changes will be visible in the newest version 4.60.
