### ISSUE TITLE
Set base currency for auctions

### ISSUE THREAD

**Issue by TTomu** [grandnode/grandnode#736]
Set base currency for auctions view at "my account". Currently currency is changed without calculating currency rate.

**Comment by dborovsky** [comment]
@TTomu  I can do it. Is still actual?

**Comment by TTomu** [comment]
@dborovsky, sure it is still open.

**Comment by PatrykPorabik** [comment]
@dborovsky I would rather check this issue #735 . As GrandNode is multi vendor (Multi seller) e-commerce platform, it can be a great feature. This task with base currency may be problematic and we suppose that it can bring many different problems.
