### ISSUE TITLE
Auction Log for admin panel

### ISSUE THREAD

**Issue by sepehrland** [grandnode/grandnode#737]
Admin should has the ability to see the log of auctions and also manage the auctions, who add bids, who wins, delete some fake bids, flag the winner for the second one if the winner does not pay, and many more which related to the auctions.

**Comment by PatrykPorabik** [comment]
Bids can be deleted and view from the "Bids" tab in admin panel, as on the screenshot below:
![image](https://user-images.githubusercontent.com/16773025/72782611-80771b00-3c24-11ea-968d-3b613007429b.png)


In the Activity Log, you will also have information about new bid:
![image](https://user-images.githubusercontent.com/16773025/72782592-6c331e00-3c24-11ea-940a-5f4d53d76710.png)

Is not enough for you?
