### ISSUE TITLE
Cache consolidation

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [grandnode/grandnode#738]
### Problem
Our application does not handle concurrent requests very well. The bottleneck is the caching mechanism/strategy. Redis is indeed a very powerful tool but we need to change the way we use it.

Our current strategy is to cache very small pieces of info, which usually substitute a database query.

Currently, a single request of a anonymous user to the main page of the SAMPLE DATABASE will cause around 40 commands to be executed on redis.  
If these take 1ms to complete a roundtrip (issue command, fetch result, network trip, etc), a single request timer will start at acceptable's 40ms.  
When we talk about 5 concurrent requests, the initial timer jumps to 200ms due to the fact that redis is not concurrent. Things get ugly pretty quick.

### Suggestion
We should add to our cache mechanism coarser levels of cache. Put together with #712 a lot of redis roundtrips can be avoided, improving greatly the performance of concurrent requests, without hamstringing the store manager.  
For backward compatibility, I think we should not delete any already used keys, only add the new "consolidate information" keys.

**Comment by PatrykPorabik** [comment]
In my opinion, advanced cache customization should be done on end user store. Each bigger store, that would rely on i.e Redis, probably will have own scenario of ideal caching. Platform should deliver the most basic and extendable configuration.

**Comment by Leonardo-Ferreira** [comment]
How exactly would that customisation happen?

I agree that the platform should be extensible, but I don't think we should deliver only the most basic configuration. I think quite the opposite. I believe we should deliver the most complete and configurable solution possible, in a way that no one would feel the need to extend it. I know that is not possible, but we should aim for it anyway, leaving the extensibility door wide open.
