### ISSUE TITLE
Can we agree on not caching default values?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [grandnode/grandnode#739]
### Proposal
If we agree on not caching `default(T)` and `null` values, we can save on 2 fronts: cache size and roundtrip time.

### Suggestion  
We do this by setting the `DefaultValueHandling` value of `JsonSerializerSettings` to `Ignore` on the `Set` methods. Even better results can be obtained if we do not store empty enumerations/lists/collections.

### Example given  
A key with the pattern `Grand.product.id-{0}` is around 4.5kb. Using the proposed method, the size of the key dropped to 2.1kb (more than 50%).

**Comment by jzabroski** [comment]
What happens if the default value changes across releases?

**Comment by Leonardo-Ferreira** [comment]
`default(T)` is not defined by "us". `default(T)` is defined the .Net Core runtime itself. Whatever the runtime identifies as `default(T)` will be ignored by the serialisation on the way out and re-established on the way in, whatever other value will be persisted!  
Tou can check [this table](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/default-values-table) fot the complete list.
