### ISSUE TITLE
expand and select queries

### ISSUE THREAD

**Issue by rezabashiri** [grandnode/grandnode#741]
I'm wondering to expand product by categories or pictures but after testing all kind of queries im  respond by error :

"The query specified in the URI is not valid. Property 'categories' on type 'Default.ProductDto' is not a navigation property or complex property. Only navigation properties can be expanded."

**Comment by KrzysztofPajak** [comment]
@rezabashiri Unfortunately "expand" and "select" method for OData with MongoDB is not working correctly (is not supported).

**Comment by rezabashiri** [comment]
would you please show a way to fetch all categories of a product or pictures of a product and i need a way to filter products base on category , i couldnt find any sample about those
