### ISSUE TITLE
fetch all categories of a product or pictures of a product 

### ISSUE THREAD

**Issue by rezabashiri** [grandnode/grandnode#742]
would you please show a way to fetch all categories of a product or pictures of a product and i need a way to filter products base on category , i couldnt find any sample about those

**Comment by KrzysztofPajak** [comment]
Try use this query:
/odata/product?$filter=Categories/any(c:c/CategoryId eq 'xxx')

But you must have a patch https://github.com/grandnode/grandnode/commit/d444d2173382bce9c07d3a82b5d44b8daf531c3b

**Comment by rezabashiri** [comment]
thank you so much , but how about my first question to have pictures of a product in product list ,
I just want to show products in my app with their pictures without extra fetch request , isnt it possible?

**Comment by KrzysztofPajak** [comment]
You can only list pictures only from product entity: /odata/product('ID')

**Comment by KrzysztofPajak** [comment]
If you need get access to pictures entity, please try this:
http://docs.grandnode.com/operations-with-pictures

**Comment by rezabashiri** [comment]
I mean how to have list of products with their pictures ?
it could be helped to have them separately

**Comment by KrzysztofPajak** [comment]
Product entity should contains information about pictures.

**Comment by rezabashiri** [comment]
without expand query ? in default it has all data?

**Comment by rezabashiri** [comment]
this is what /odata/product?$filter=Categories/any(c:c/CategoryId eq '5e158b566bd67f2ef83efd08') responsed to me !
`{
    "@odata.context": "http://localhost:16592/odata/$metadata#Product",
    "value": [`

**Comment by KrzysztofPajak** [comment]
Please check on beta version 4.60

**Comment by rezabashiri** [comment]
these are branches on git 
`

origin/HEAD -> origin/develop                                                                                                                                                                                                     origin/Release-4.00                                                                                                                                                                                                               origin/Release-4.10                                                                                                                                                                                                               origin/Release-4.20                                                                                                                                                                                                               origin/Release-4.20.01                                                                                                                                                                                                            origin/Release-4.30                                                                                                                                                                                                               origin/Release-4.40                                                                                                                                                                                                               origin/Release-4.50                                                                                                                                                                                                               origin/develop                                                                                                                                                                                                                    origin/issue-cache-objectsettings                                                                                                                                                                                                 origin/issue-image
--


`

**Comment by rezabashiri** [comment]
it work correctly but what about my first question ? to have pictures of a product without extra fetch ?
now just pictureId exists in productDetail
