### ISSUE TITLE
\Grand.Data\Grand.Data.csproj' does not exist.	Grand.Plugin.Api.Extended	

### ISSUE THREAD

**Issue by rezabashiri** [grandnode/grandnode#744]
While i trying to build Grand.Plugin.Api.Extended	 i've got Grand.Data.csproj does not exist error

**Comment by PatrykPorabik** [comment]
Hi, 
It’s caused by a fact that we’ve removed Grand.Data project. We’ve moved it to Grand.Core project, you can always check the commit with that changes.

**Comment by rezabashiri** [comment]
Yes I got it , but i cant find the repository of gran.plugin.api.extended to clone newset version
