### ISSUE TITLE
Document is weak and outdated

### ISSUE THREAD

**Issue by rezabashiri** [grandnode/grandnode#745]
There is some inconsistencies at documents like you mentioned expand query in documents but it couldnt be used by odata and mongodb Or there is no any document about how to use Web.Api.Extend plugin !!!

I'm really intrested in grandnode but the i think its child yet and its not proper to use it as primary shop

**Comment by KrzysztofPajak** [comment]
This kind of questions please post on our forums https://grandnode.com/boards
GitHub is issued for development work items.
