### ISSUE TITLE
Low stock activity Unpublish

### ISSUE THREAD

**Issue by callmejm** [grandnode/grandnode#746]
In Admin Backend > Catalog > Product > Inventory > Low stock activity

I have set 
![image](https://user-images.githubusercontent.com/6957533/72271372-b97e2100-3661-11ea-98ce-e7eb730f4a1b.png)

Product should Unpublish in home page , but it still showing , so what exactly is Unpublish mean at here ? or I miss out any setting

**Comment by PatrykPorabik** [comment]
Have you reduced the stock quantity manually in admin panel? Are you able to provide step by step instruction how to simulate this issue? I'm not able to reproduce it on our demo.

**Comment by callmejm** [comment]
@PatrykPorabik Hi ,thanks for reply, yes I reduce the stock quantity manually in admin panel, so you suggest i set quantity to 1, and checkout as a new order for testing ?

**Comment by PatrykPorabik** [comment]
Exactly.
