### ISSUE TITLE
loginvalidator.cs rules return unvalidated for customers

### ISSUE THREAD

**Issue by rezabashiri** [grandnode/grandnode#754]
in validators\common\loginvalidator.cs when api need to get token and validate a customer it through RuleFor rules and because you check :
` RuleFor(x => x).MustAsync(async (x, context) =>
            {
                if (!string.IsNullOrEmpty(x.Email))
                {
                    var userapi = await userApiService.GetUserByEmail(x.Email.ToLowerInvariant());
                    if (userapi != null && userapi.IsActive)
                    {
                        var base64EncodedBytes = System.Convert.FromBase64String(x.Password);
                        var password = System.Text.Encoding.UTF8.GetString(base64EncodedBytes);
                        if (userapi.Password == encryptionService.EncryptText(password, userapi.PrivateKey))
                            return true;
                    }
                }
                return false;
            }).WithMessage(("User not exists or password is wrong"));`

it will be always false but when a api user want to get token due to not only it is customer but also its api user it will pass all the rules 

`  RuleFor(x => x).MustAsync(async (x, context) =>
            {
                if (!string.IsNullOrEmpty(x.Email))
                {
                    var customer = await customerService.GetCustomerByEmail(x.Email.ToLowerInvariant());
                    if (customer != null && customer.Active && !customer.IsSystemAccount)
                        return true;
                }
                return false;
            }).WithMessage("Customer not exist");`

So you have take care about if just a  customer wanna take token , token should be created !

**Comment by PatrykPorabik** [comment]
GrandNode API was developed as an admin API. If you want to use it, just create an API user in Admin panel. If you want to create an API for users, you need to develop it.

**Comment by rezabashiri** [comment]
may i be as contributor to help development phases on grandnode?

**Comment by dborovsky** [comment]
Sure.
