### ISSUE TITLE
Do we a performance issue?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [grandnode/grandnode#762]
When I'm running on my local machine, I find the performance of the site "lacking" when I have redis cache on and I simulate multiple users concurrently.

Do we have actual field data to compare and contrast?

**Comment by PatrykPorabik** [comment]
What do you mean by multiple users concurrently? What's the approx. number of users?

**Comment by Leonardo-Ferreira** [comment]
Currently I use Fiddler to issue 5 concurrent request, each simulating a unregistered user accessing the home page. These take around 7 sec to be completed. (of course the request happen after the application is warmed-up and the cache is already in place, aka: no hits on the database)

**Comment by PatrykPorabik** [comment]
To be honest, we've removed Redis today. You can download the develop branch and check the newest approach to caching.

**Comment by ghominejad** [comment]
What about 1000 concurrent users? what is your approach for a distributed caching solution?

Thanks
