### ISSUE TITLE
Use swagger to testing web api.

### ISSUE THREAD

**Issue by dborovsky** [grandnode/grandnode#763]
I think  testing web api methods will  be more comfortable and easy use with swagger.

**Comment by Leonardo-Ferreira** [comment]
That is a good point. How are the test being conducted now?

**Comment by dborovsky** [comment]
Now we can only test use tools as postman or another aditional tools. With swagger we don't need aditional tools. You will open just link in browser and test api. 

Example swagger https://petstore.swagger.io/

**Comment by PatrykPorabik** [comment]
Thanks for suggestion and discussion. We can think about it in the newest release. We don't have final roadmap yet for the 4.70 version.

**Comment by PatrykPorabik** [comment]
@Leonardo-Ferreira , @dborovsky  Please look at the following commit - d49ee84, we've implemented Swagger in the project. When you run the develop 4.80 version, you can enable API and Swagger in appsettings.json file, then you can navigate to yourstore.com/swagger/index.html and see the result :)
