### ISSUE TITLE
Extend the sitemap functionality - images

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#766]
Extend the sitemap functionality - images

**Comment by dborovsky** [comment]
Guys, I will do it... If will have any question, will ask you.

**Comment by dborovsky** [comment]
@PatrykPorabik  How can I find settings sitemap in admin panel?

**Comment by PatrykPorabik** [comment]
@dborovsky In my opinion it should be always included in sitemap. Regardless of any kind of setting.

**Comment by dborovsky** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/3728303/76813943-89423280-680a-11ea-8e59-7e7ee3439b79.png)


This is current sitemap. Which images must be include in sitemap?

**Comment by PatrykPorabik** [comment]
Current sitemap contains also products, blog posts if you set them, so you've provided only small part of sitemap. In my opinion things that you've missed are the most important in the store - products and blog and images related with that parts of store. Basically, answer for your question is probably in the first paragraph of sitemap image description in Google Docs. First of all you should know why it's worth to include images in the sitemap - the main benefit is that search engines will easier discover images that may have otherwise not been found. And I suppose, it should be enough to know that it should include as many images as possible. But maybe someone has different opinion. Secondly you should check how it should looks, it's described in the article below.

https://support.google.com/webmasters/answer/178636?hl=en

**Comment by dborovsky** [comment]
@PatrykPorabik  thank you.  I was sick this days. Now I feel like superman and  investigating now.

**Comment by dborovsky** [comment]
@PatrykPorabik Thanks. I think better solution for images to generate separate sitemaps xml files. 

Now I started with images for products.
For example will be created following files:
sitemap-images-1.xml
sitemap-images-2.xml
and etc
where 1, 2 ... product id.

What do you think?

**Comment by PatrykPorabik** [comment]
But what's the purpose of creating new sitemap files, if scenario presented in docs assumes that you only extend the current flow with new field. I don't think so creating a new file is efficient in that case.
