### ISSUE TITLE
Questions about shopping and payment

### ISSUE THREAD

**Issue by leeolevis** [grandnode/grandnode#771]
hi sir, i want to ask two questions

1.How to temporarily turn off the shopping function

2. How to pay after the shopping process is completed
(That is, the order is successfully sent to the background, and the payment is confirmed by other methods)

**Comment by KrzysztofPajak** [comment]
Hi,
Your issue is not related with code, please send question on our board [https://grandnode.com/boards](url)

**Comment by leeolevis** [comment]
> Hi,
> Your issue is not related with code, please send question on our board [https://grandnode.com/boards](url)

ok tks 
I opened the broad correctly. The link of the link you gave is a bit wrong. It can be corrected for the convenience of others.

**Comment by KrzysztofPajak** [comment]
Fixed :)
