### ISSUE TITLE
4.30 . Had a problem in google anayltics commerical configuration

### ISSUE THREAD

**Issue by marmarKamel** [grandnode/grandnode#776]
i want to activate google anayltics commerical widget plugin in Grand node version 4.30 
i already added configuration but still not working 

i already added google analytics in main store configuration and it works well but we added commerical plugin it still not work 

need help

**Comment by PatrykPorabik** [comment]
Hi, 
The question is not related with the code, please post it on our community forum here: https://grandnode.com/boards
