### ISSUE TITLE
Additional shipping charge on pickup

### ISSUE THREAD

**Issue by pati1892** [grandnode/grandnode#794]
**Describe the bug**
If I set Additional shipping charge it is added to in store pickup as well

**To Reproduce**
1. Add Additional shipping charge to product
2. Add Product to shopping cart
3. Select Pickup
4. Additional shipping charge is not ignored

**Expected behavior**
Additional shipping charge is ignored

**Additional context**
Version 4.60

**Comment by PatrykPorabik** [comment]
Hi,

In fact it's expected behavior of this feature. It's additional cost, charged independently from shipping method. It doesn't matter if it's pickup point or not.
