### ISSUE TITLE
StoreClosed InvalidOperationException

### ISSUE THREAD

**Issue by kdlslyv** [grandnode/grandnode#797]
**Describe the bug**

When accessing a closed store, the following exception is thrown:
```
InvalidOperationException: Could not find an IRouter associated with the ActionContext. If your application is using endpoint routing then you can get a IUrlHelperFactory with dependency injection and use it to create a UrlHelper, or use Microsoft.AspNetCore.Routing.LinkGenerator.
```

**To Reproduce**
1. Close the store
2. Logout
3. Navigate to start page

**Expected behavior**
StoreClosed page is shown

**Additional context**

- Probably caused by `CheckAccessClosedStoreAttribute.cs`
- Line 142, add IUrlHelperFactory to the constructor and use it instead of `new UrlHelper(context)` to fix the issue

Cannot try it out locally - otherwise I wouldn't hesitate submit a pull request; sorry!
Keep up the great work with GrandNode 👍

**Comment by KrzysztofPajak** [comment]
Thanks, fixed!

Best Regards
Krzysztof
