### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by codetrove-development** [grandnode/grandnode#798]
Hi,

I can't work out if grandnode would support my requirement.

I would like to make a market place similar to amazon - where I own the overall domain, call it compay A.
Other companies can have their own store ie companyB.companyA.com, which I believe you support. However, my question is does it support product matching like amazon.

Example: https://www.amazon.co.uk/Greatideal-Adjustable-Environmental-Bodybuilding-Professional/dp/B0868LY4DY/ref=sxbs_sxwds-stvp?cv_ct_cx=barbell&dchild=1&keywords=barbell&pd_rd_i=B0868LY4DY&pd_rd_r=6fb20c9e-5cb3-4cd6-b639-72608f902ef4&pd_rd_w=H0m66&pd_rd_wg=0h76A&pf_rd_p=d9b87ec0-c7c2-464c-b8a6-2e7b5576127a&pf_rd_r=YTR38SCYG7QW7726W5KH&psc=1&qid=1587202995&sr=1-4-718396de-69ac-46a0-9195-9669ab0086b2

You click "New (6) from £40.87" and now the customer can view all different companies that are selling this item. You can also click on the individual company to see their own store and what other items that store is selling.  

I would like this, preferably with more improvements. If it's already supported please let me know, otherwise if anyone would like to change it into a feature request I am happy to collaborate, if my testing goes well and I decide grandnode is definitely the right choice for my business. i am a net core dev.

**Comment by KrzysztofPajak** [comment]
Hi @codetrove-development 
The question is not related with the code, please post it on our community forum here: https://grandnode.com/boards

Best Regards
Krzysztof
