### ISSUE TITLE
Sitemap doesnt work

### ISSUE THREAD

**Issue by pati1892** [grandnode/grandnode#799]
**Describe the bug**
Altough the Sitemap is Enabled (under Admin/Setting/AllSettings; commonsettings.sitemapenabled = True), the Sitemap is not displayed.

**To Reproduce**
1. Admin/Setting/AllSettings
2. Select 'commonsettings.sitemapenabled'
3. Set Value to true, and save
4. clear cache
5. Got to /sitemap and you get redirected to Homepage

**Expected behavior**
Sitemap works if enabled

**Additional context**
- Version 4.60
- Apparently the [FromService] annotation is missing in the methods Sitemap and SitemapXml in CommonController

**Comment by PatrykPorabik** [comment]
Hi,
In fact it has been fixed after beta of 4.60. As you can see in the develop branch it's annotation was added to sitemapxml :)
