### ISSUE TITLE
Enhanced Forum Plugin

### ISSUE THREAD

**Issue by primalfear** [grandnode/grandnode#800]
Hi GrandNode team,

I am busy evaluating at using GrandNode as a base for an up coming project and currently investigation extensibility specifically.

One of the things we are looking at is to enhance the forums a little bit, so that we can support some of the following:
- Private Forums / Topics / threads / discussions 
   By this i mean users, need to be logged in to via the forums.
   Need to be either invited or request access to a forum / discussion before being able to view or contribute.
- Users to be able to create new forums / thread (from the front-end)
- And a couple of other things.

I would like to add in these enhancements via the recommended exensiblity points within the platform, so that we can maintain backward compatibility with the "MainLine" Project and Potentially be able to contribute back some of our components.

My Questions...

- Is the plugin system the correct why to go about this? (I am assuming yes) -> and have started mocking out the plugin, and so far I have it detecting, and a configuration page, kinda, sorta working :)

- What "Type" of plugin would i be creating (I am assuming Widget) But this feels to fall outside of current plugin types. (as this feels like i would almost need to over-ride some of the templates as well or would i just render out the various views from the plugin into ) 

- Any General Pointers that can be given, that could help achieve the outlined goals would be greatly appreciated.

Apologies if these questions are a little naive, I am still getting into the code base, and it's quiet a thing, and i have not yet fully absorbed all of it. :)

**Comment by PatrykPorabik** [comment]
Hi,

Yes, plugin system is the correct way to achieve your goals. If I were you I would use the Misc type or Widget. However, I suppose Misc type is better. In the case of tips, I would base this plugin on customer roles. You can disable access to the forum with specified customer roles, then prepare a form or something to request access to it. Maybe in this way? Check how the ACL work in GrandNode, it may be helpful for you.

**Comment by primalfear** [comment]
Awesome... Thanks for the pointers.
The documentation doesn't mention the "Misc" Type, but i will dig about and see what I can find.

Am going to close this issue. :)
