### ISSUE TITLE
Add message template for payment refund

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#819]
Add notification for user when the payment has been refunded

**Comment by NikolaSvobodova1983** [comment]
Hello @PatrykPorabik 
Could you please tell me, how can I enable false payment method for making an order in develop mode?
![image](https://user-images.githubusercontent.com/64211725/81415062-328d1100-9148-11ea-934e-bd95272eed4e.png)
I remember previously it was possible to pay with some fake payment method, how can I enable it now?
(I tried to pay with reward points, but also failed)
Thank you.
