### ISSUE TITLE
Question - How do you add custom validation to the create product request?

### ISSUE THREAD

**Issue by TecorraDevelopment** [grandnode/grandnode#834]
I have created a plugin which registers IProductViewModelService to an extension class. On InsertProductModel(model) this then checks if a product already exists for the model GTIN and if so throws an error. Unfortunately I didn't realise throwing an error would actually cause it to render the exception message in the view!

I see no way of being able to return a failure to the UI without modifying ProductController in Grand.Web.Areas.Admin.Controllers, which is obviously a problem.

Please can someone let me know if there's a different way I should be doing this? I require server side validation, not front end. Thanks!

**Comment by TecorraDevelopment** [comment]
I have also found this article http://docs.grandnode.com/data-validation but it's out of date. Searching through validators in the code base I can't find any way of registering validation to the ProductModel in Areas/Admin/Controllers/ProductController without changing the controller code and adding a validation attribute

**Comment by KrzysztofPajak** [comment]
@TecorraDevelopment 
Sorry for documentation, next week we will update.
If you need add new rules for product validators just use IValidatorConsumer<ProductModel> and add by method AddRules (BaseGrandValidator<ProductModel> validator)

    public class GtinValidation : IValidatorConsumer<ProductModel>
    {
        public void AddRules(BaseGrandValidator<ProductModel> validator)
        {
            validator.RuleFor(x => x.Gtin).NotEmpty()
                .WithMessage("Gtin is required");
        }
    }

**Comment by TecorraDevelopment** [comment]
@KrzysztofPajak ah that works pefectly, thanks! Last question - Is there also an extension option for adding more properties to the productmodel or will I need to extend... a lot?

**Comment by KrzysztofPajak** [comment]
@TecorraDevelopment 
Try to generic attributes
