### ISSUE TITLE
3.90 - Problem with PayPal payment

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#84]
Problem with PayPal payment

`Could not load file or assembly 'PayPalCoreSDK, Version=1.7.0.0, Culture=neutral, PublicKeyToken=5b4afc1ccaef40fb' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

**Comment by nop4you** [comment]
Fixed
