### ISSUE TITLE
Shipping plugin for brazil correios

### ISSUE THREAD

**Issue by marcelowu** [grandnode/grandnode#841]
https://github.com/nopCommerceBrasil/NopBrasil.Plugin.Shipping.Correios

https://cws2.correios.com.br/static/swagger/?url=/precoprazoservice/rs/swagger.json#!/Nacional/listaPrecosPrazos

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PatrykPorabik** [comment]
How can we help with this and how is this related with GrandNode?
