### ISSUE TITLE
Allow to adding labels on orders

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#845]
Allow adding labels on orders.

Labels should allow you to filter orders by them.

**Comment by dborovsky** [comment]
Hi Pa

I   would like to help with this task. Is it still relevant?

**Comment by TTomu** [comment]
@dborovsky any help is welcome

**Comment by dborovsky** [comment]
> Allow adding labels on orders.

Do you mean admin in admin panel can add labels or custommers?

**Comment by dborovsky** [comment]
@TTomu can you please give more info. To finish this feature I need undestand completly logic. Thanks

**Comment by PatrykPorabik** [comment]
@dborovsky Hello Dmitriy, to be honest, we have a clear vision for that feature and we would like to make it with the rest of the team. We've already spent some time on the analysis and discussions, so I'm not sure if it would be worth explaining the whole idea again. Maybe you would like to take another task?

**Comment by dborovsky** [comment]
Sure. No problems. Which task or bugs are now in priority?

**Comment by PatrykPorabik** [comment]
I will talk with the rest of the team and let you know. Please give me some time.

**Comment by dborovsky** [comment]
Any news?

**Comment by PatrykPorabik** [comment]
Yes, you can take the order labels. 

It should look like Customer Tags. You should create new table - Order Tags, then on the Orders list, there should be a possibility to filter orders by tags. Then on the order details page, you should be able to assign tags to orders. Please remember about the resource strings, Please also remember to use the same notation as before on each admin page.

**Comment by dborovsky** [comment]
yea. thanks. have already started. Adding and changing labels will be in admin panel as admin. Correct?

**Comment by PatrykPorabik** [comment]
Yes, of course in the admin panel. It's for administrators.

**Comment by dborovsky** [comment]
@PatrykPorabik  Must I implement page "Tags list" like on tab Orders?

**Comment by PatrykPorabik** [comment]
I think tags on order details should be provided as a simple field, below Order status or order number. The whole list of orders tags, where you can specify all tags, should be the same as "Products tags", "Customer tags" as an independent menu item in the sidebar menu.

**Comment by dborovsky** [comment]
I've already finished. I want to import localization resources from  EN_470_480.nopres.xml to defaultResources.grandres.xml

I select language - import file - uploading - EN_470_480.nopres.xml - importwas without errors. 

But new localization resources were not imported to defaultResources.grandres.xml. 
How should I correct update localization?

**Comment by PatrykPorabik** [comment]
You should manually update the EN_470_480.xml and defaultResources.grandres.xml files.

**Comment by dborovsky** [comment]
I created PR. 

Do I need implement Searching orders by tag name? 

Except filter is everything has finished.
