### ISSUE TITLE
Cant install language packs!

### ISSUE THREAD

**Issue by Goldenstarc** [grandnode/grandnode#848]
**Describe the bug**
Cant install language packs

**To Reproduce**
1.Use docker image
2.Download any pack like arabic or german
3. Go to 'language'
4. Add language
2. Click on 'Import resourse'

**Expected behavior**
Import language and user can use it.

**behavior**
On version 4.4 and above :
you`ll get no error ! just every thing without language !

On version 4.3 and below
it shows different error on each try

Try 1:
'.', hexadecimal value 0x00, is an invalid character. Line 54, position 17.
Try 2  (same xml file)
'', hexadecimal value 0x12, is an invalid character. Line 39, position 16.
and so on....

**What did i do**
1.didnt change any code (docker image)
2.tried on different versions
3.didnt change lang pack which downloaded from grandnode site.

**additional try**
1.go to English lang.
2.click on Export resources
3.make new lang
4.import that resources
5. Error!

**Comment by PatrykPorabik** [comment]
Hi @Goldenstarc 
Can you confirm that the problem also occurs on the latest version of GrandNode 4.70?

**Comment by Goldenstarc** [comment]
sure!

**Comment by PatrykPorabik** [comment]
Unfortunately, I'm not able to reproduce the issue. I've checked this feature while ago on Docker and I'm able to export/import any language pack - German, Arabic, English.
