### ISSUE TITLE
consider moving API to a separate project

### ISSUE THREAD

**Issue by scharada** [grandnode/grandnode#853]
if not used, it's still loaded.
if used, it makes the web app heavier 
if modifications are needed, the whole app needs to be compiled and redeployed ...
the reasons a multiple.
please consider it. it just makes sense.

**Comment by PatrykPorabik** [comment]
@scharada thanks for idea, we were thinking about that and we will for sure back to it.

**Comment by KrzysztofPajak** [comment]
Done

**Comment by scharada** [comment]
Hi @PatrykPorabik 
good work . but i think i did not describe my suggestion well enough.
what i meant is have the api totally separated from the main project so it can run in its own process. 
the API project today is still part of and runs within the main app space and context ... that is the issue.
thanks.
