### ISSUE TITLE
separate front end from admin

### ISSUE THREAD

**Issue by scharada** [grandnode/grandnode#854]
have you though about making the front end and the admin area separate web application ?
the front end would be blazing fast and would cost much less in cloud deployment.
doing so also would allow the backend to be accessed only when needed by users who manage the sites... admins and vendors. 
it would also be easier to have 2 separate areas, one for site admins and one for vendors making views and UI really different and can be customized without affecting each others.

**Comment by PatrykPorabik** [comment]
Related with #496
