### ISSUE TITLE
how to add videos on Grandnode?

### ISSUE THREAD

**Issue by marcelowu** [grandnode/grandnode#861]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PatrykPorabik** [comment]
Videos can be added in the TinyMCE editor with Media uploader. However, it's not a technical question, so in the future, please post this kind of questions on our community forum here: [https://grandnode.com/boards](https://grandnode.com/boards)

![image](https://user-images.githubusercontent.com/16773025/84859305-28c2cb80-b06d-11ea-9d89-54961cdac778.png)
