### ISSUE TITLE
EncryptText Bug

### ISSUE THREAD

**Issue by fuat-tek** [grandnode/grandnode#873]
I am using GrandNode 4,70. When I do credit card integration, I get the error in the method below.
The Substring method fails. The reason for the error is that the length of the entered value is 16 characters. It was made over 24 characters while doing substring. Do you have any information about this subject?
This problem gives an error both in the payment page and in the order detail in the administration panel.

public virtual string EncryptText(string plainText, string encryptionPrivateKey = "")
        {
            if (string.IsNullOrEmpty(plainText))
                return plainText;

            if (String.IsNullOrEmpty(encryptionPrivateKey))
                encryptionPrivateKey = _securitySettings.EncryptionKey;

            var tDESalg = TripleDES.Create();

            var w = new ASCIIEncoding().GetBytes(encryptionPrivateKey.Substring(0, 24));

            tDESalg.Key = new ASCIIEncoding().GetBytes(encryptionPrivateKey.Substring(0, 24));
            tDESalg.IV = new ASCIIEncoding().GetBytes(encryptionPrivateKey.Substring(16, 8));

            byte[] encryptedBinary = EncryptTextToMemory(plainText, tDESalg.Key, tDESalg.IV);
            return Convert.ToBase64String(encryptedBinary);
        }

It worked when I edited it as below.
  public virtual string EncryptText(string plainText, string encryptionPrivateKey = "")
        {
            if (string.IsNullOrEmpty(plainText))
                return plainText;

            if (String.IsNullOrEmpty(encryptionPrivateKey))
                encryptionPrivateKey = _securitySettings.EncryptionKey;

            var tDESalg = TripleDES.Create();

            var w = new ASCIIEncoding().GetBytes(encryptionPrivateKey.Substring(0, 16));

            tDESalg.Key = new ASCIIEncoding().GetBytes(encryptionPrivateKey.Substring(0, 16));
            tDESalg.IV = new ASCIIEncoding().GetBytes(encryptionPrivateKey.Substring(8, 8));

            byte[] encryptedBinary = EncryptTextToMemory(plainText, tDESalg.Key, tDESalg.IV);
            return Convert.ToBase64String(encryptedBinary);
        }

**Comment by KrzysztofPajak** [comment]
Fixed [https://github.com/grandnode/grandnode/commit/49a46320a57c792037e57089584afe3fed003233#diff-3d7a898adb26c4aa779a6b416a3a0c80](https://github.com/grandnode/grandnode/commit/49a46320a57c792037e57089584afe3fed003233#diff-3d7a898adb26c4aa779a6b416a3a0c80)
