### ISSUE TITLE
Inconsistency in ASP.NET version on Docs site

### ISSUE THREAD

**Issue by BurialOrchid** [grandnode/grandnode#883]
https://docs.grandnode.com/getting-started is saying that GrandNode is based on ASP.NET Core 3.1 but
https://docs.grandnode.com/what-is-grandnode and https://docs.grandnode.com/introduction says that it is ASP.NET Core 2.2.
Please change that :)
![image](https://user-images.githubusercontent.com/46527470/87197679-c4f19280-c2fa-11ea-903b-ee880cc2f9aa.png)
![image](https://user-images.githubusercontent.com/46527470/87197787-cde26400-c2fa-11ea-89b3-502e3aeda127.png)
![image](https://user-images.githubusercontent.com/46527470/87197572-b905d080-c2fa-11ea-9f7c-1b535f9e9b4b.png)

**Comment by TTomu** [comment]
@BurialOrchid Thank you for notification. Corrected.
