### ISSUE TITLE
Prooduct's image upload failed

### ISSUE THREAD

**Issue by dborovsky** [grandnode/grandnode#884]
**Describe the bug**
Prooduct's image upload failed

**To Reproduce**
1. Go to admin panel as Vendor
2. Click on products - add new
3. Click Pictures - add new picture
4. Select picture for Loading

**Screenshots**
![screen1](https://user-images.githubusercontent.com/3728303/87257391-42580700-c4a3-11ea-9905-39db84d958fb.png)

**Desktop (please complete the following information):**
 - Browser Opera

**Additional context**
The file  has format jpg

**Comment by TTomu** [comment]
I just made test on our demo, and seems to work fine.
![image](https://user-images.githubusercontent.com/16773048/87276162-0db67080-c4e0-11ea-88b4-b113ac16c6e6.png)
Are you able to simulate issue at our demo? Remember please that demo is reseted.

**Comment by Illia-M** [comment]
Have similar(visually) problem, nginx(revers proxy) brake image upload larger then configured max request/body/file size(1MB for me). Which settings for demo?

**Comment by TTomu** [comment]
> brake image upload larger then configured

So that is by design. If need to enlarge, need to change at the media settings.

**Comment by dborovsky** [comment]
@TTomu  My file is less than 1 mb. 

I set to user role as vendor and conected this user to Vendor1. 

I get this error if I sign in as this user and try to add new product. 

I checked in google crome and see following error:

![screen1](https://user-images.githubusercontent.com/3728303/87302473-25aae600-c51a-11ea-992c-3853038dd5d1.png)

**Comment by TTomu** [comment]
> I set user's role as vendor and conected this user to Vendor1.
> 
> I get this error if I sign in as this user and trying to add new product.

That is exactly this same way I have test it on our demo
![image](https://user-images.githubusercontent.com/16773048/87305113-3e190180-c516-11ea-98a6-d28675e1c1cf.png)
Even working fine for larger images
![image](https://user-images.githubusercontent.com/16773048/87305198-60ab1a80-c516-11ea-90a5-9c100f669ac9.png)
Working even for impersonate session.
What version of GrandNode you are using?

**Comment by dborovsky** [comment]
I use last version 4.6 
Strange...  I will continue test with another account

**Comment by TTomu** [comment]
> I use last version 4.6

Last version is 4.70, and tested on that version. 
Issue was able to reproduce at 4.60, as said - new version got it fixed.

**Comment by PatrykPorabik** [comment]
@dborovsky Dmitriy, it's an ACL issue. Please give Vendor permissions to Manage files. Go to Admin panel -> Configuration -> Access Control List and check the following permission - Admin area. Manage Files. It should solve the problem.
