### ISSUE TITLE
Plugin Install error

### ISSUE THREAD

**Issue by BeliaevFiodor** [grandnode/grandnode#886]
**Describe the bug**
When I made plugin it doesn't appear in admin menu. If I try to install plugin manually I got error:
Exception: This plugin doesn't support the current version - 4.80

**To Reproduce**
create any simple plugin and try to install it from admin menu: Configuration->Local Plugins -> Upload

**Expected behavior**
I think plugin must be installed automatically, but even manually installation doesn't fix problem

**Screenshots**
![image](https://user-images.githubusercontent.com/45309486/87424545-c960c880-c5e4-11ea-8653-9afce136409d.png)

**Comment by PatrykPorabik** [comment]
You've probably made plugin for GrandNode 4.70 and try to install it on 4.80 version. It's not possible. Please check the Description.txt file of your plugin. And the second case is, that it's not recommended to use 4.80 version. It's version currently during the development phase, before tests, so you may face some bugs or other problems. If you want to make a plugin for GrandNode it's recommended to use the latest stable version, so 4.70. Furthermore, we won't publish the 4.80 plugins or themes at the moment.
