### ISSUE TITLE
CosmosDB compatibility

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [grandnode/grandnode#887]
**Is your feature request related to a problem? Please describe.**
From a I.T. point of view, managing a mongo cluster is not an easy thing to do. Even for structured companies. On the other hand, azure offers Cosmos with a mongo API that is 100% managed.

**Describe the solution you'd like**
I would like that GrandNode to be compatible with CosmosDB.

**Describe alternatives you've considered**
No alternatives

**Additional context**

**Comment by PatrykPorabik** [comment]
Some time ago, when we wanted to create a support for CosmosDB, it turned out that CosmosDB is not 100% "compatible with MongoDB, which made it impossible to support. However, it's still in our mind and we want to make the CosmosDB support in GrandNode.

**Comment by Leonardo-Ferreira** [comment]
yeah... trying to "set up shop" I stumbled on 2 very important issues.

The first one is a technical one: some of the indexes definitions are not supported. Given a crude mongodb scenario that would be a blocker, but Cosmos has already some indexing going on behind the scene and perhaps that would suffice

the second one is a monetary one. Due to the large number of collections, the cheapest it runs is aprox $4 an hour which turns out to be almost $3k a month... that's a pretty expensive empty database...

**Comment by ScratZa** [comment]
Hi Everyone

Im assuming Using the MongoDB api with AWS DocumentDB will result in the same issues mentioned above? not sure if anyone has explored this as yet

**Comment by PatrykPorabik** [comment]
Hello Everyone,

I would like to announce that AWS DocumentDB and CosmosDB are supported in GrandNode v2. You can get it here: [https://github.com/grandnode/grandnode2/](https://github.com/grandnode/grandnode2/)
