### ISSUE TITLE
Add possibility to edit custom robots.txt file via admin panel

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#898]
We should add the possibility to edit custom robots.txt file via admin panel

**Comment by dborovsky** [comment]
Hi I would like to help with this task. Is it ok?

**Comment by PatrykPorabik** [comment]
Hi,
Sure. It's ok. Do you have any questions? You can use the Custom CSS or Custom JS views as a template for that feature.

**Comment by dborovsky** [comment]
Yes, I can and have questions.  How must be implemented this feature on admin panel? 
You mean additional tab, than open editor with robot.txt file, admin can edit and after click save? 
Can you share more details?

**Comment by PatrykPorabik** [comment]
@dborovsky please go to Admin Panel and look at how Custom JS and Custom CSS in the System tab work. Robots.txt should work similarly. It has to be a custom robots.txt file, not the original one. By default, the editor should be empty of course. Please check also this part of the project: https://github.com/grandnode/grandnode/blob/37916214f54fe29bbe5cf9cbe183581d12c5a732/Grand.Web/Areas/Admin/Controllers/CommonController.cs#L683

**Comment by dborovsky** [comment]
codemirror library dosen't suport hint robot.txt. I will implement without hint. Ok?

**Comment by PatrykPorabik** [comment]
Of course, it would be hard to suggest anything with hints in the case of robots.txt file.

**Comment by dborovsky** [comment]
what path should a file be saved to?

**Comment by PatrykPorabik** [comment]
@dborovsky please check how it works now. Because custom.robots.txt file is available in GrandNode. Just add possibility to edit it from the admin panel.

**Comment by dborovsky** [comment]
Check please pr #917
