### ISSUE TITLE
move to use AspNetcore.Identity for managing users, user profiles  and roles.

### ISSUE THREAD

**Issue by scharada** [grandnode/grandnode#904]
it's the standard and using it opens a whole lot of new doors for improvements we cannot do today like managing claims and permissions in a flexible way instead of having hardcoded permissions and roles...
an aspnet.identity for mongodb exists and is very stable.
it also integrates nicely with identityserver

**Comment by TTomu** [comment]
After discussion, we decided to not implement it.

**Comment by scharada** [comment]
@TTomu  ok. may i know the reason(s) ? curious to know what led to that decision.
