### ISSUE TITLE
Allow adding of Picture URL to database

### ISSUE THREAD

**Issue by rahsharm77** [grandnode/grandnode#905]
Hello,

I am working on this wonderful platform and I have encountered into a problem which is that I am trying to figure out how to add my inserted Picture URL to the mongoDB collection. 

For example: When I add a product and upload an Picture, is there a way that I can insert the URL created for that picture(be it local, AWS or Azure) to the Product collection (or Picture collection is also an option).

1st attempt:  In the method: **Task< Picture > InsertPicture** in Services/Media/PictureService.cs, I am not able to figure out how to create the URL for the picture since I cannot find the **_id** of the inserted picture. Once the URL is created then I  can store in the Picture collection.

2nd attempt: In the method: **Task< Product > InsertProductModel** in Areas/Admin/Services/ProductViewModelService.cs, I added an entity called ProductImageURL ad I am doing something like this: **product.ProductImageURL = "https://bucketname.s3.amazonAws.com/filename";** before calling **await _productService.InsertProduct(product);** . Now my question is that how can I insert the picture URL in this field? 

If anyone has done this and would like to share their solution, that would be great.

Thanks

**Comment by TTomu** [comment]
Amazon S3 is supported by default. 
URL is not possible to store, as Amazon returns a response with a picture that is scalable already.

**Comment by rahsharm77** [comment]
I have plugged in the S3 fuctionality and that is working correctly but the point that I am trying to make is that how can I store pictures URL associated to a product so that I can expose endpoint for an API that I am trying to create to get all products with their pictures. I do not want to write the entire logic that Grandnode is performing to return back the URL for picture and its associated thumbnail. If I could just insert the generated URL before inserting into Picture collect

**Comment by rahsharm77** [comment]
o

**Comment by rahsharm77** [comment]
Reopening the issue since I accidently closed it earlier.
