### ISSUE TITLE
Staff - Bulk Edit Product is not accessible when the assigned store will be removed

### ISSUE THREAD

**Issue by Illia-M** [grandnode/grandnode#909]
**Describe the bug**
can not open Bulk product edit page. All other pages work fine.

**To Reproduce**
1. Go to Bulk product edit
2. See white page of error

**Expected behavior**
No NRE and page open

**Desktop (please complete the following information):**
 - Firefox

**Additional context**
In logs:
System.NullReferenceException: Object reference not set to an instance of an object. at Grand.Web.Areas.Admin.Services.ProductViewModelService.PrepareBulkEditListModel() in D:\GrandnodeGit\grandnode\Grand.Web\Areas\Admin\Services\ProductViewModelService.cs:line 1896 at Grand.Web.Areas.Admin.Controllers.ProductController.BulkEdit() in D:\GrandnodeGit\grandnode\Grand.Web\Areas\Admin\Controllers\ProductController.cs:line 1386 at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Grand.Framework.Middleware.WorkContextMiddleware.Invoke(HttpContext context, IWorkContext workContext) in D:\GrandnodeGit\grandnode\Grand.Framework\Middleware\WorkContextMiddleware.cs:line 73 at Grand.Framework.Middleware.StoreContextMiddleware.Invoke(HttpContext context, IStoreContext storeContext) in D:\GrandnodeGit\grandnode\Grand.Framework\Middleware\StoreContextMiddleware.cs:line 44 at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Grand.Framework.Middleware.PoweredByMiddleware.InvokeAsync(HttpContext context, IPoweredByMiddlewareOptions options) in D:\GrandnodeGit\grandnode\Grand.Framework\Middleware\PoweredByMiddleware.cs:line 27 at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by PatrykPorabik** [comment]
Hi @Illia-M 

Which version of GrandNode do you use? Are you able to simulate it on our demo.grandnode.com?

**Comment by Illia-M** [comment]
I use 4.70, i will try investigate what happens and try to reproduce, but NRE that must be very easy to diagnose when you has stack trace)

**Comment by Illia-M** [comment]
I remove one of the store

var store = (await _storeService.GetAllStores()).Where(x => x.Id == storeId).FirstOrDefault();
NRE line -->>      model.AvailableStores.Add(new SelectListItem { Text = store.Shortcut, Value = store.Id.ToString() });

Try use .Single(x => x.Id == storeId) instead of .Where(x => x.Id == storeId).FirstOrDefault();

**Comment by Illia-M** [comment]
Remove Staff role from user and problem is gone

**Comment by PatrykPorabik** [comment]
.Single won't solve the problem at all. It's a more complicated case, to be honest, you shouldn't delete the store if you have a staff user assigned to it. For now, we've implemented the above-listed solution. It will prevent to throw the Object reference.. error. But we will think about more sophisticated validation.
