### ISSUE TITLE
External Auth redirect url problem

### ISSUE THREAD

**Issue by Illia-M** [grandnode/grandnode#910]
Hi, both Google and Facebook auth requests sends redirect_url in http scheme, not in https.
All shop settings configured as site with SSL
![1](https://user-images.githubusercontent.com/64944310/90872719-bdb3af00-e3a5-11ea-9d6a-fbd3ae3cdaed.PNG)
![2](https://user-images.githubusercontent.com/64944310/90872723-be4c4580-e3a5-11ea-81a0-10f08ef74547.PNG)

**Comment by PatrykPorabik** [comment]
Have you configured the appsettings.json file? If you install SSL, you need to set up a few things in it according to your server. 
https://github.com/grandnode/grandnode/blob/develop/Grand.Web/App_Data/appsettings.json#L2

**Comment by Illia-M** [comment]
I set "UseHttpXForwardedProto" to true. I should change something more?
"UseHttpsRedirection" need configuration in Nginx and documentation says that for WebApi redirects is bad practice.

**Comment by PatrykPorabik** [comment]
Try with "UseHttpXForwardedProto" to False and "UseForwardedHeaders" to True.

**Comment by Illia-M** [comment]
> 
> 
> Try with "UseHttpXForwardedProto" to False and "UseForwardedHeaders" to True.

This change solve my problem! Thank you!)
