### ISSUE TITLE
Limit staff access to specific store

### ISSUE THREAD

**Issue by gelinski** [grandnode/grandnode#912]
I created the following scenario:

- Created two distinct stores at the same GN instance (using multi store concept), stores A and B;
- Added two customers as Staff (A/B);
- Logged in with user A in store A;
- Created some stuff, like products/categories;
- Entered in store B with user A;

Expected behavior:
User A couldn't access the content of site B or get accessed to admin panel of this. Consider that stores A and B are competitors between each other and user A cannot view contents such campaigns (discounts) or product list (where shows the stock and prices).

Is there some additional configuration to do, that I can say to GN "User A is employee of Store A and cannot view content from its competitor", or still it have to be developed?

Ps.: I'm testing with GN 4.70

**Comment by PatrykPorabik** [comment]
Hi, 

In GrandNode you don't have customers assigned to a specific stores. We don't have also any plans to support or implement that feature.
