### ISSUE TITLE
Allow managing cookies preference 

### ISSUE THREAD

**Issue by KrzysztofPajak** [grandnode/grandnode#915]
Allow managing cookies preference.

**Comment by dborovsky** [comment]
I would like to help with this task. Can you share more details about managing cookies?

**Comment by PatrykPorabik** [comment]
@dborovsky Thanks a lot, however, Krzysztof is already working on that.

**Comment by dborovsky** [comment]
@PatrykPorabik Tell me which tasks are in priority now?
