### ISSUE TITLE
[Question] Marketplace source code

### ISSUE THREAD

**Issue by fatagun** [grandnode/grandnode#920]
Hello,

Is the marketplace (https://grandnode.com/extensions) source code available for public?

Thanks.

**Comment by PatrykPorabik** [comment]
Sure, on each product you can mark checkbox "Source code" you will receive them after purchase.

**Comment by fatagun** [comment]
Hey, thanks for prompt response.

I was actually asking for the marketplace code itself where vendors register their soft/hard products for selling. 

I meant the source code of (https://grandnode.com/extensions) this page. 

Thanks again

**Comment by PatrykPorabik** [comment]
It's standard version of GrandNode. We didn't implement anything special. So if you want to create the same marketplace,e just get GrandNode and that's all :) We've only made a custom theme.

**Comment by fatagun** [comment]
Thanks man. :)
