### ISSUE TITLE
config grandnode with nginx reverse proxy

### ISSUE THREAD

**Issue by zach88** [grandnode/grandnode#929]
**Describe the bug**
The function GetStoreLocation in WebHelper return http scheme on OnePageCheckout while the System information page show the "Http request scheme" as https and "Http scheme is https" as true.

The GetStoreLocation function only return https scheme on OnePageCheckout if UseHttpXForwardedProto is set true and UseForwardedHeaders is set false in appsettings.json but System information page show the "Http request scheme" as http and "Http scheme is https" as false.

**To Reproduce**
1. Set true UseForwardedHeaders in appsettings.json
2. Check out the System information page and OnePageCheckout render the url as http
3. Try to complete the order 
4. You are redirected to the Cart page

**Expected behavior**
the function GetStoreLocation in WebHelper.cs return https url and System information page show the "Http request scheme as https" and "Http scheme is https" as true

**Comment by PatrykPorabik** [comment]
Hello @zach88 
Have you configured the SSL in the admin panel? You should go to Admin -> Configuration -> Stores, edit your store and mark "Use SSL" checkbox. Then provide the secure URL with https:// protocol. In the case of appsettings.json, it's enough to set UseHttpXForwardedProto false and UseForwardedHeaders true.

**Comment by PatrykPorabik** [comment]
And please post this kind of question on our community forum. It's not a development question.
