### ISSUE TITLE
Different product price for each currency

### ISSUE THREAD

**Issue by mehmetcantas** [grandnode/grandnode#941]
Hey, I know it's already in grandnode, but it's not I'm talking about that. If you want to set different prices for each currency you have ,currently you can't. From my experiences this is the neccessary feature for product price management.

**Things to be done :** 

- Store owners can set different prices for each currency. This allow us to flexibility on product price management.
- For to do this we can create a ProductPrice table. This table columns will be : ProductId, CurrencyId, OldPrice, Price, SpecialPrice, SpecialPriceStartDate and SpecialPriceEndDate.

**Comment by PatrykPorabik** [comment]
To be honest similar task already exists on our roadmap #355
