### ISSUE TITLE
Country restriction for topic pages

### ISSUE THREAD

**Issue by mehmetcantas** [grandnode/grandnode#942]
Is your feature request related to a problem? Please describe.

If store owner working with multiple countries topic page contents can be changed depend on country. E.g. : return request rules can be changed for local or abroad orders or something like that.

Describe the solution you'd like
A restriction table can be create for topics.

Describe alternatives you've considered
Additional context
I can help for this feature if you consider to add to 5.0 version.

**Comment by KrzysztofPajak** [comment]
@mehmetcantas I suggest using multi-store features.
Most of the settings support multi-store. Every store will be assigned to your country's location.

**Comment by dogo-mehmetcantas** [comment]
Yes, but it's can be complex for store owners. This feature already done for payment and shipping methods if we add this also for topic pages store owners easly manage them topics

**Comment by mehmetcantas** [comment]
Yes, but it's can be complex for store owners. This feature already done for payment and shipping methods if we add this also for topic pages store owners easly manage them topics

**Comment by PatrykPorabik** [comment]
Limited to store feature is also available as a table. Directly on topic creation/edition page. So I suppose every store owner will handle it easily. You are able to do that with a [Multi-tenant plugin](https://grandnode.com/advanced-multi-tenant), which is available on our marketplace.
