### ISSUE TITLE
GDPR logs for customers and newsletter subscriptions

### ISSUE THREAD

**Issue by mehmetcantas** [grandnode/grandnode#950]
**Is your feature request related to a problem? Please describe.**
Currently GDPR options or logs doesnt exist in GrandNode.

**Describe the solution you'd like**
GDPR accept date, GDPR accepted by ip address and current GDPR confirm status can be added on both Customer and NewsletterSubscriptions tables

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by KrzysztofPajak** [comment]
@mehmetcantas 
Please check this link:
[https://grandnode.com/gdpr-in-e-commerce-how-to-meet-requirements-with-grandnode](https://grandnode.com/gdpr-in-e-commerce-how-to-meet-requirements-with-grandnode)

and the latest feature
[https://grandnode.com/new-release-grandnode-4800-beta](https://grandnode.com/new-release-grandnode-4800-beta)
"Allow managing cookies preference"
