### ISSUE TITLE
Refactor ProductReviewService - add new method

### ISSUE THREAD

**Issue by dborovsky** [grandnode/grandnode#962]
I would like a bit change ProductReviewService.

I implement test for UpdateProductReviewTotalsCommandHandler

I can't mock following line in Handle method:
`await _productReviewRepository.Collection.Find(new BsonDocument("ProductId", request.Product.Id)).ToListAsync();`

I can't setup mock object for method Find of MongoCollection:

 `_mongoCollectionMock.Setup(x => x.Find(It.IsAny<FilterDefinition<ProductReview>>(), It.IsAny<FindOptions>()));`

Get error becasue extention method can't be setup in mock object.

I want to create new method GetAllProductReviewsByProductId for ProductReviewService/ 

And using this method in Handle method to get all reviews. Than I can wrap all logic of ProductReviewRepository inside this method and I'll be able to create mock object for object of type ProductReviewService and use in test. 

Dear collegues of GrandNode core team if you a agree, tell me.

**Comment by KrzysztofPajak** [comment]
@dborovsky Sure, you can extend interface  IProductReviewService.
