### ISSUE TITLE
Admin panel crash when enabling right to left.

### ISSUE THREAD

**Issue by usr338** [grandnode/grandnode#963]
**Describe the bug**
Admin panel crash when enabling right to left. side bar menu show nothing and main content is messed up in version 4.8 beta

**To Reproduce**
please go to Administration area, 
then Configuration -> Languages, 
and click on language. 
check "Right to left" box.

**Desktop :**
 - all browsers

**Comment by PatrykPorabik** [comment]
Which version of GrandNode,? We've checked it on the newest one, and everything works as expected.

**Comment by usr338** [comment]
> 
> 
> Which version of GrandNode,? We've checked it on the newest one, and everything works as expected.

In 4.8 beta version problem exist.
 because the version of bootstrap-rtl which is use in project is 3.3.6 but normal bootstrap is 4.5.2

**Comment by KrzysztofPajak** [comment]
Thanks!
We updated bootstrap-rtl library
