### ISSUE TITLE
multi-vendor - rather than multi-product logic. multi-seller - one product.

### ISSUE THREAD

**Issue by talhakaanozkan** [grandnode/grandnode#967]
### Is your feature request related to a problem? Please describe.
**multi-vendor - rather than multi-product logic. multi-seller - one product.**

### Describe the solution you want
**Enter the products from admin. Can I do so that the seller can only enter price / stock / stock code on the products? Is there a plug-in?**

**Comment by KrzysztofPajak** [comment]
@talhakaanozkan Unfortunately, we do not have such a plugin.
