### ISSUE TITLE
I don't want users with "Guest" to use the system.

### ISSUE THREAD

**Issue by talhakaanozkan** [grandnode/grandnode#968]
** Is your feature request related to a problem? Please describe. **
I don't want users with "Guest" to use the system. I want only those who have logged in to be able to see and buy the products. how can I do that ?

** Describe the solution you want **
Settings can be added to the settings so that only members can view the products.

**Comment by KrzysztofPajak** [comment]
Could you please post this kind of questions on our forum?

**Comment by talhakaanozkan** [comment]
> Could you please post this kind of questions on our forum?

I shared the topic under the title of suggestions and feedback.
