### ISSUE TITLE
Odata with SeoFriendlyUrlsForLanguagesEnabled don't work

### ISSUE THREAD

**Issue by benys** [grandnode/grandnode#970]
With turned on SeoFriendlyUrlsForLanguagesEnabled Odata don't work. For example /odata/$metadata is not found.

**To reproduce:**
1. fetch stable version
2. turn on SeoFriendlyUrlsForLanguagesEnabled
3. turn on Api
4. try to open /odata/$metadata 

**Additional context**
If I comment pattern in GenericUrlRouteProvider and RouteProvider related with SeoFriendlyUrlsForLanguagesEnabled Odata start working. I can't find out where is the problem.

**Comment by TTomu** [comment]
Thank you, we will check this.

**Comment by benys** [comment]
@KrzysztofPajak it looks that work.
