### ISSUE TITLE
can you help me install these plugins

### ISSUE THREAD

**Issue by marcelowu** [grandnode/grandnode#971]
already used these plugins, this is working? I don't know how to install on ubuntu, can you help me install.
Grandnode shipping rate computation plugin from brazilian postal company. (v4.60+)
https://github.com/rafaelboschini/Grand.Plugin.Shipping.Correios

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TTomu** [comment]
That is an extension, not part of the project. 
We recommend contacting with Rafael. He`s very helpful and I`m sure he will help you with it.
