### ISSUE TITLE
[Area ("Admin")] in plugins.

### ISSUE THREAD

**Issue by talhakaanozkan** [grandnode/grandnode#972]
**Describe the bug**
https://github.com/grandnode/grandnode/commit/1d8bc592ce25a243825899c1abb64267832abea2
I updated those in this task myself. I noticed while examining. stuck as [Area ("Admin")] in plugins.

**Comment by KrzysztofPajak** [comment]
Yes, It's by design.
In the plugins we do not want add reference to the project Grand.Web so it can be written that.
