### ISSUE TITLE
Adding Monetization From Vendor

### ISSUE THREAD

**Issue by hassanelsherbiny** [grandnode/grandnode#973]
Let Store Owner Get Benefits From Registered Vendors By Adding Fix fee Or Percentage Fee For Each Vendor To Be Calculated in separated Report By Store Owner.
We Can Also Make It on/off by choosing Settings for store owner to select whether to choose.

**Comment by PatrykPorabik** [comment]
What's the purpose of it? The store owner is able to get a commission from each sale. is it not enough?

**Comment by hassanelsherbiny** [comment]
how can store owner set commission? and how can store owner know how much commission he got from specific vendor?

**Comment by PatrykPorabik** [comment]
Please ask this question on [our community forum](https://grandnode.com/boards), it's not related to application technical issues.
