### ISSUE TITLE
There are some bugs and clutter in Admin Panel (backoffice)  when layout is right to left

### ISSUE THREAD

**Issue by usr338** [grandnode/grandnode#976]
**Describe the bug**
Browse button doesn't work during importing data(such as product list or language resources , ...) from excel files.

**To Reproduce**
1. Go to 'Admin Panel'
2. Click on 'Configuration -> Languages '
3. Select any language exist in table.
4. Select Right-to-left -> save
5. when layout changes to right to left -> select import Resources
6. try to click 'Browse' button  and see the error

**Expected behavior**
'Browse button should allow to select file'

**Desktop **
 - Browser Chrome

**Additional context**
Same behavior can be seen in any place that import from excel is possible. 

By the way in right to left layout, color of the tab pages and side menu(in pages like Products) are different from left to right layout. also side menu is in wrong place( In fact page layout should be mirrored in most senarios for right to left layout ).

**Comment by PatrykPorabik** [comment]
@dan269 can you look at it?

**Comment by usr338** [comment]
by the way, this problem exist in version 4.8
