### ISSUE TITLE
Add Start/End date fot Topics (Pages) 

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#982]
Add Start/End date fot Topics (Pages)

**Comment by badijm** [comment]
Can you elaborate? What would be a purpose ?

**Comment by PatrykPorabik** [comment]
To be honest, purpose is very simple :) Topics (Pages) are nothing less or more than static pages. Sometimes, you want to run a limited time landing page, for example for halloween promo, so you would like to make it limited with start and end date.

**Comment by badijm** [comment]
Got it. Just wanna ask is there any pitfall about handling migration?
Or just simply - add 2 columns to **Domain** class & run re-installation (also update `CodeFirstInstallationService`)?

**Comment by PatrykPorabik** [comment]
In my opinion, If the user doesn't need it, the start/end date field may be empty. A similar mechanism is in the blog post for example.

**Comment by badijm** [comment]
@PatrykPorabik I've decided to keep them NOT NULL, as it easier to handle in code. 
But on the other handle - I put default values for these columns.

**Comment by badijm** [comment]
Hi, @PatrykPorabik any updates about my PR?

**Comment by PatrykPorabik** [comment]
Hi, @badijm. We will look at it :) We had some internal work.
