### ISSUE TITLE
Duplicated param in API $metadata: Action: CreateProductSpecification, param: SpecificationAttributeOptionId 

### ISSUE THREAD

**Issue by marcobrigantiglobalis** [grandnode/grandnode#988]
In Release 4.7
Duplicated parameter in API $metadata: Action: CreateProductSpecification, param: SpecificationAttributeOptionId 

To Reproduce (if debuggin in local):
http://localhost:16592/odata/$metadata
1. Go to  http://localhost:16592/odata/$metadata
2. Search CreateProductSpecification
3. Can you see the duplicated SpecificationAttributeOptionId  parameter

This causes some problems.

**Comment by PatrykPorabik** [comment]
Hello,

It has been fixed in the 4.80.0 version.
