### ISSUE TITLE
If the product is unpublished, it disappears from the Bestsellers report

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#989]
If the product is unpublished, it disappears from the Bestsellers report

**Comment by badijm** [comment]
Hi, I can pick this item to implement.

**Comment by badijm** [comment]
#990

**Comment by PatrykPorabik** [comment]
Hi @badijm,

It's not so simple, currently, you also removed the published flag from the frontend bestsellers section, so on the homepage, we will see also unpublished products. We've missed it, but we use the same method for generating bestsellers on frontend and backend.

**Comment by badijm** [comment]
Okay, I will check source code
