### ISSUE TITLE
The "ReturnRequestStatus" language setting is missing.

### ISSUE THREAD

**Issue by talhakaanozkan** [grandnode/grandnode#992]
**Describe the bug**
I think the picture explains the event clearly.
The "ReturnRequestStatus" language setting is missing. "_localizationService" should be added.

**Screenshots**
![image](https://user-images.githubusercontent.com/24568732/97169884-df615600-179b-11eb-92de-cf1b43041c68.png)
![image](https://user-images.githubusercontent.com/24568732/97169714-8d203500-179b-11eb-9801-df5fe933748e.png)

**Comment by PatrykPorabik** [comment]
Thanks for the notification, fixed.
