### ISSUE TITLE
"microsoft.azure.storage" has been deprecated

### ISSUE THREAD

**Issue by talhakaanozkan** [grandnode/grandnode#994]
**Describe the bug**
"microsoft.azure.storage" has been deprecated. Are you going to do something for it?

**Screenshots**
![image](https://user-images.githubusercontent.com/24568732/97697800-928dc000-1ab8-11eb-9265-2920b0cafd0c.png)

**Comment by PatrykPorabik** [comment]
@talhakaanozkan Sure, we will update the packages in the newest version of GrandNode. As always, when any kind of package becomes deprecated.

**Comment by PatrykPorabik** [comment]
Here is the opened work item - #995

**Comment by talhakaanozkan** [comment]
great, thanks for your quick response.
